import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { isolatedConceptId } from "./concept-identity";
import { runResearchWorker, RESEARCH_LIMITS, type ResearchJob, type ResearchStore } from "./research-worker";
import { computeEvidenceHash, computeFormulaHash, type TrendOutfitFormula, type TrendStyleEvidence } from "./schema";
import { runManualFirstStylingWorkflow } from "./manual-workflow";
import { proveDistinctFormulaJobs, traceFormulaImageLifecycle } from "./isolated-image-jobs";
import { selectApprovedFormulaSetFromRows } from "./repository";

test("mocked linen isolated search completes research, atomic six-formula approval and six images",async()=>{
  const conceptId=isolatedConceptId("linen");assert.equal(conceptId,isolatedConceptId(" Linen "));assert.match(conceptId,/^[0-9a-f-]{36}$/);
  const job:ResearchJob={id:isolatedConceptId("linen job"),concept_id:conceptId,canonical_keyword:"linen",requesting_market:"BR",season:"summer",attempts:1,max_attempts:3};
  const evidenceRows:any[]=[];const marketEvidenceRows:any[]=[];let completed:any=null;let retries=0;let claims=0;let providerInvocations=0;const searchCalls:any[]=[];const authoritativeWrites=0;
  const store:ResearchStore={async claim(){claims++;return job},async saveMarketEvidence(_job,batch){marketEvidenceRows.push(...batch.markets)},async insertEvidence(rows){evidenceRows.push(...rows)},async checkpointEvidence(_job,data){completed=data},async retry(){retries++}};
  const markets=["IN","US","GB","FR","IT","DE","JP","KR","AU","BR","SG","AE"] as const;const interestProvider={async discover(){providerInvocations++;const score:{[key:string]:number}={JP:98,FR:94,IT:91,BR:65};return {schemaVersion:"repo-pytrends-market-discovery-v1" as const,provider:"google_trends_pytrends" as const,canonicalKeyword:"linen",generatedAt:"2026-07-20T00:00:00.000Z",cacheHit:false,providerCalls:13,maximumProviderCalls:18,markets:markets.map((market)=>({market,normalizedInterest:score[market]||2,recentMomentum:score[market]||2,confidence:score[market] ? .9 : .1,observationCompleteness:score[market]?1:.2,providerTimestamp:"2026-07-20T00:00:00.000Z",retryInformation:{attempts:1,maxAttempts:3,rateLimited:false,retryAfterSeconds:null,nextRetryAt:null},failureReason:null}))}}};
  const searchProvider={async search(input:any){searchCalls.push(input);const host=input.audience==="women"?"vogue.example":"gq.example";const second=input.audience==="women"?"elle.example":"retailer.example";return [{title:`${input.audience} linen shirt trousers ${input.market}`,url:`https://www.${host}/wear?utm_source=x`,domain:host,shortExtract:"White linen shirt tucked into wide leg linen trousers with brown sandals and belt",publishedAt:"2026-07-01T00:00:00.000Z",market:input.market,language:input.language},{title:`Local ${input.audience} linen tailoring ${input.market}`,url:`https://${second}/${input.market}/${input.language}`,domain:second,shortExtract:"Blue linen shirt layered with tailored linen trousers and loafers",publishedAt:"2026-06-25T00:00:00.000Z",market:input.market,language:input.language}]}};
  const worker=await runResearchWorker({workerId:"test",store,interestProvider:interestProvider as any,searchProvider,now:new Date("2026-07-20T00:00:00.000Z"),authoritativeMarketPlanLoader:async()=>null});
  assert.equal(worker.status,"evidence_ready");assert.ok(worker.marketDiscovery);assert.equal(claims,1);assert.equal(providerInvocations,1);assert.equal(worker.marketDiscovery.providerCalls,13);assert.ok(worker.marketDiscovery.providerCalls<=RESEARCH_LIMITS.maxMarketDiscoveryProviderCallsPerKeyword);assert.equal(marketEvidenceRows.length,12);assert.deepEqual(worker.marketPlan.strongestMarkets,["JP","FR","IT"]);assert.deepEqual(worker.marketPlan.researchMarkets,["JP","FR","IT","BR"]);assert.equal(worker.marketPlan.evaluatedMarkets.length,12);assert.ok(searchCalls.some((call)=>call.region==="JP"&&call.language==="ja"));assert.ok(searchCalls.some((call)=>call.region==="BR"&&call.language==="pt"));assert.ok(searchCalls.length<=RESEARCH_LIMITS.maxStylingSearchCallsPerKeyword);assert.ok(evidenceRows.length>=4);assert.equal(new Set(evidenceRows.map((row)=>row.source_domain)).size,4);assert.ok(evidenceRows.every((row)=>row.published_at&&row.observed_at&&row.garment_pairings.length>=2&&row.quality_score&&row.recency_score&&row.market_relevance_score));assert.ok(evidenceRows.every((row)=>!row.source_url.includes("utm_")));assert.ok(completed?.evidenceHash);assert.match(completed.selectedReasons.BR.join(" "),/requesting_user_market/);assert.equal(retries,0);
  const evidence=evidenceRows.map((row)=>({...row,trend_id:null})) as TrendStyleEvidence[];const evidenceHash=computeEvidenceHash(evidence);const setId=isolatedConceptId("linen set");const slots=["easy_entry","current_uniform","editorial_push"] as const;
  const generate=async()=>["women","men"].flatMap((audience)=>slots.map((slot,index)=>{const base={id:isolatedConceptId(`linen ${audience} ${slot}`),concept_id:conceptId,set_id:setId,canonical_keyword:"linen",audience:audience as "women"|"men",formula_slot:slot,title:`${slot} linen`,items:[{role:"top",garment:index===0?"linen shirt":index===1?"linen polo":"linen waistcoat",silhouette:index===2?"oversized":"relaxed",colour:"white",material:"linen",styling_instruction:"tuck the front into the waistband"},{role:"bottom",garment:index===0?"tailored trousers":index===1?"wide leg trousers":"pleated shorts",silhouette:index===0?"straight tailored":index===1?"wide leg":"relaxed above knee",colour:"navy",material:"linen",styling_instruction:"wear at the natural waist"}],footwear:index===2?"brown leather sandals":"black leather loafers",accessories:["woven leather belt"],occasion:"daytime",climate:"warm humid",season:"summer",region:"BR",why_it_works:"The breathable linen texture connects both garments while the defined waist and grounded footwear control the relaxed volume.",evidence_ids:evidence.map((item)=>item.id),confidence:.88,evidence_hash:evidenceHash,generated_at:"2026-07-20T00:00:00.000Z",valid_until:"2026-09-15T00:00:00.000Z",review_status:"pending_review" as const};return {...base,formula_hash:computeFormulaHash(base)}})) as TrendOutfitFormula[];
  let approvedCache:TrendOutfitFormula[]=[{...(await generate())[0],id:isolatedConceptId("old formula"),review_status:"approved"}];let approvalCalls=0;const result=await runManualFirstStylingWorkflow({enabled:true,autoEnqueueImages:true,research:async()=>({evidence:evidenceRows}),generate,approve:async(formulas)=>{approvalCalls++;assert.equal(formulas.length,6);const next=formulas.map((formula)=>({...formula,review_status:"approved" as const}));approvedCache=next;return next},enqueue:async(jobs)=>{assert.equal(jobs.length,6)}});
  assert.equal(result.status,"completed",JSON.stringify(result));assert.equal(approvalCalls,1);assert.equal(approvedCache.length,6);assert.equal(new Set(approvedCache.map((formula)=>`${formula.audience}:${formula.formula_slot}`)).size,6);assert.equal(result.jobs.length,6);assert.equal(proveDistinctFormulaJobs(result.jobs),true);assert.equal(new Set(result.jobs.map((job)=>job.metadata.formulaId)).size,6);assert.equal(new Set(result.jobs.map((job)=>job.storage_path)).size,6);assert.ok(result.jobs.every((job)=>job.metadata.formulaHash&&job.metadata.evidenceHash&&job.metadata.audience&&job.metadata.formulaSlot));for(const jobRow of result.jobs){const lifecycle=traceFormulaImageLifecycle(jobRow);for(const stage of Object.values(lifecycle))assert.deepEqual(stage.metadata,jobRow.metadata);assert.equal(lifecycle.published.storage_path,jobRow.storage_path);assert.equal(lifecycle.published.database_identity,jobRow.formula_id);}const migration=await readFile(new URL("../../database/028_trend_styling_market_research.sql",import.meta.url),"utf8");assert.match(migration,/generated_fashion_images_formula_uidx/);assert.match(migration,/set_generated_formula_identity/);assert.match(migration,/formula_count<>6/);assert.equal(selectApprovedFormulaSetFromRows(approvedCache,"women").length,3);assert.equal(authoritativeWrites,0);

  let imageEnqueueCalls=0;const formulaOnly=await runManualFirstStylingWorkflow({enabled:true,autoEnqueueImages:false,research:async()=>({evidence:evidenceRows}),generate,approve:async(formulas)=>formulas.map((formula)=>({...formula,review_status:"approved" as const})),enqueue:async()=>{imageEnqueueCalls++}});assert.equal(formulaOnly.status,"completed");assert.equal(formulaOnly.imageEnqueued,false);assert.equal(imageEnqueueCalls,0);
});
