import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { computeEvidenceHash, computeFormulaHash, trendOutfitFormulaSchema, type TrendOutfitFormula, type TrendStyleEvidence } from "./schema";
import { validateFormula, validateFormulaSet, validateSixFormulaBatch } from "./validation";
import { buildLailaPersonalisationPrompt, buildLailaTrendUrl, readLailaTrendContext } from "./laila-handoff";
import { buildFormulaOutfitPrompt, formulaImageVariant, validateFormulaOutfitObservation } from "../images/formula-outfit";
import { trendStylingConfig } from "./config";
import { selectStylingResearchMarkets } from "./market-selection";
import { deduplicateStylingSources } from "./evidence-deduplication";

const evidence = (domain: string): TrendStyleEvidence => ({ id: randomUUID(), trend_id: 7, canonical_keyword: "barrel jeans", audience: "women", region: "IN", season: "monsoon", garment_pairings: ["barrel jeans and fitted shirt"], silhouettes: ["barrel leg"], materials: ["denim"], colours: ["indigo"], footwear: ["loafers"], accessories: ["belt"], styling_techniques: ["fitted top balances volume"], source_url: `https://${domain}/wear`, source_domain: domain, short_extract: "Observed outfit pairing.", published_at: "2026-06-28T00:00:00.000Z", observed_at: "2026-07-01T00:00:00.000Z", quality_score: .9, recency_score: .95 });
const sources = [evidence("vogue.in"), evidence("gqindia.com")];
function formula(slot: TrendOutfitFormula["formula_slot"], garment = "barrel jeans"): TrendOutfitFormula {
  const base = { trend_id: 7, canonical_keyword: "barrel jeans", audience: "women" as const, formula_slot: slot, title: `${slot} denim`, items: [{ role: "bottom", garment, silhouette: "curved barrel leg", colour: "indigo", material: "rigid denim", styling_instruction: "show the high waist" }, { role: "top", garment: slot === "easy_entry" ? "fitted poplin shirt" : slot === "current_uniform" ? "ribbed polo shirt" : "sculpted waistcoat", silhouette: "close fitted", colour: "white", material: "cotton", styling_instruction: "tuck into the waistband" }], footwear: "black leather loafers", accessories: ["slim leather belt"], occasion: "daytime", climate: "warm humid", season: "monsoon", region: "IN", why_it_works: "The close upper half makes the curved denim volume legible while the dark shoe anchors the exaggerated proportion.", evidence_ids: sources.map((item) => item.id), confidence: .88, evidence_hash: computeEvidenceHash(sources), generated_at: "2026-07-10T00:00:00.000Z", valid_until: "2026-10-10T00:00:00.000Z", review_status: "approved" as const };
  return { ...base, formula_hash: computeFormulaHash(base) };
}

test("strict formula schema rejects unknown fields", () => assert.equal(trendOutfitFormulaSchema.safeParse({ ...formula("easy_entry"), surprise: true }).success, false));
test("rejects vague garments", () => assert.match(validateFormula(formula("easy_entry", "statement piece"), sources, new Date("2026-07-20")).errors.join(" "), /vague/i));
test("rejects semantic mismatch", () => assert.match(validateFormula({ ...formula("easy_entry"), canonical_keyword: "crochet dress" }, sources, new Date("2026-07-20")).errors.join(" "), /not visibly expressed/i));
test("rejects stale evidence/formula", () => assert.match(validateFormula({ ...formula("easy_entry"), valid_until: "2026-07-19T00:00:00.000Z" }, sources, new Date("2026-07-20")).errors.join(" "), /stale/i));
test("requires independent evidence domains", () => assert.match(validateFormula(formula("easy_entry"), [sources[0], { ...sources[1], source_domain: sources[0].source_domain }], new Date("2026-07-20")).errors.join(" "), /independent/i));
test("three slots are distinct and audience-separated", () => { assert.equal(validateFormulaSet([formula("easy_entry"), formula("current_uniform"), formula("editorial_push")]).valid, true); assert.equal(validateFormulaSet([formula("easy_entry"), { ...formula("current_uniform"), audience: "men" }, formula("editorial_push")]).valid, false); });
test("hashes are stable and change with evidence/formula content", () => { assert.equal(computeEvidenceHash(sources), computeEvidenceHash([...sources].reverse())); assert.notEqual(formula("easy_entry").formula_hash, formula("current_uniform").formula_hash); });
test("Laila URL preserves exact context", () => { const url = buildLailaTrendUrl({ trendId: "7", keyword: "barrel jeans", formulaId: sources[0].id, audience: "women", market: "IN", source: "trend-card" }); const parsed = readLailaTrendContext(new URLSearchParams(url.split("?")[1])); assert.equal(parsed?.formulaId, sources[0].id); assert.match(buildLailaPersonalisationPrompt(parsed!, ["indigo jeans"]), /wardrobe.*indigo jeans/i); });
test("formula image variants never use trend_concept and prompt includes exact outfit", () => { const value = formula("easy_entry"); assert.equal(formulaImageVariant("women"), "trend_formula_women"); assert.doesNotMatch(formulaImageVariant("women"), /concept/); const prompt = buildFormulaOutfitPrompt(value); for (const item of value.items) assert.match(prompt, new RegExp(item.garment)); });
test("outfit validator rejects flat lays and missing garments", () => assert.equal(validateFormulaOutfitObservation(formula("easy_entry"), { visibleGarments: ["barrel jeans"], trendExpressed: true, colourMaterialMatch: true, silhouetteMatch: true, contradictoryHeroGarment: false, textOrLogo: false, completeOutfit: false, flatLay: true }).accepted, false));
test("all workflow/provider flags default disabled", () => { assert.equal(trendStylingConfig.enabled, false); assert.equal(trendStylingConfig.weeklyRefreshEnabled, false); assert.equal(trendStylingConfig.autoEnqueueFormulaImages, false); assert.equal(trendStylingConfig.searchResearchEnqueueEnabled, false); });
test("page route contains no provider call and detail route contains no enqueue", async () => { const style = await readFile(new URL("../../app/api/trends/style/route.ts", import.meta.url), "utf8"); const detail = await readFile(new URL("../../app/api/trends/generate-outfit/route.ts", import.meta.url), "utf8"); assert.doesNotMatch(style, /Gemini|generateContent|createFormulaTextProvider/); const block = detail.slice(detail.indexOf('assetContext === "trend-detail"'), detail.indexOf('assetContext === "trend-card"')); assert.doesNotMatch(block, /enqueueTrendImageJob/); });
test("market selection evaluates configured 12, ranks evidence, includes requester and records reasons without PEAKING", () => { const signals = ["IN","US","GB","FR"].map((region, index) => ({ region, regionalMomentum: 90-index*10, confidence: .9, dataFreshness: 1, observationCount: 12, currentInterestPercentile: 90-index*5 })); const plan = selectStylingResearchMarkets({ signals, lifecycle: "STABLE", requestingMarket: "FR" }); assert.equal(plan.evaluatedMarkets.length, 12); assert.deepEqual(plan.strongestMarkets, ["IN","US","GB"]); assert.deepEqual(plan.researchMarkets, ["IN","US","GB","FR"]); assert.match(plan.selectedReasons.FR.join(" "),/requesting_user_market/); assert.equal(plan.insufficientMarkets.length,8); });
test("copied sources are substantially deduplicated", () => { const base = { title: "How to wear barrel jeans now", url: "https://example.com/a", domain: "example.com", shortExtract: "Wear barrel jeans with a fitted white shirt and loafers", publishedAt: "2026-07-01" }; assert.equal(deduplicateStylingSources([base, { ...base, url: "https://copy.com/b", domain: "copy.com" }]).length, 1); });
test("images cannot enqueue until all six formulas pass one batch", () => { const three = [formula("easy_entry"), formula("current_uniform"), formula("editorial_push")]; assert.equal(validateSixFormulaBatch(three).valid, false); const six = [...three, ...three.map((item) => ({ ...item, audience: "men" as const, id: undefined }))]; assert.equal(validateSixFormulaBatch(six).valid, true); });
test("61-120 day evidence is supporting only and cannot replace fresh approved formulas alone",()=>{const old=sources.map((item)=>({...item,published_at:"2026-04-01T00:00:00.000Z",observed_at:"2026-04-01T00:00:00.000Z"}));assert.match(validateFormula(formula("easy_entry"),old,new Date("2026-07-20")).errors.join(" "),/independent evidence/i);});
