from __future__ import annotations
import os, logging
from pathlib import Path
from datetime import date
import pandas as pd
from dotenv import load_dotenv
from supabase import create_client

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("forecast")

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
FORECAST_MONTHS = 12

def get_supabase():
    load_dotenv(PROJECT_ROOT / ".env")
    load_dotenv(SCRIPT_DIR / ".env", override=True)
    url = os.getenv("SUPABASE_URL") or os.getenv("NEXT_PUBLIC_SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_ANON_KEY")
    return create_client(url, key)

def fetch_india_history(client):
    all_data = []
    offset = 0
    while True:
        result = client.table("historical_trend_data")\
            .select("keyword_id, month, google_score")\
            .eq("market", "IN")\
            .range(offset, offset + 999)\
            .execute()
        batch = result.data or []
        if not batch:
            break
        all_data.extend(batch)
        offset += 1000
        if len(batch) < 1000:
            break
    return pd.DataFrame(all_data)

def fetch_keywords(client):
    result = client.table("trend_keywords").select("id, keyword, category").execute()
    return pd.DataFrame(result.data or [])

def run_forecast(series: pd.DataFrame, keyword: str) -> pd.DataFrame | None:
    from prophet import Prophet
    import warnings
    warnings.filterwarnings("ignore")

    df = series.rename(columns={"month": "ds", "google_score": "y"})
    df["ds"] = pd.to_datetime(df["ds"])
    df = df.dropna().sort_values("ds")

    if len(df) < 24:
        logger.warning("Not enough data for %s (%d points)", keyword, len(df))
        return None

    try:
        m = Prophet(
            yearly_seasonality=True,
            weekly_seasonality=False,
            daily_seasonality=False,
            changepoint_prior_scale=0.1,
            seasonality_prior_scale=10,
        )
        m.fit(df)
        future = m.make_future_dataframe(periods=FORECAST_MONTHS, freq="MS")
        forecast = m.predict(future)

        # Only return future predictions
        last_date = df["ds"].max()
        future_only = forecast[forecast["ds"] > last_date][[
            "ds", "yhat", "yhat_lower", "yhat_upper"
        ]].copy()
        future_only["keyword"] = keyword
        future_only["yhat"] = future_only["yhat"].clip(0, 100).round(1)
        future_only["yhat_lower"] = future_only["yhat_lower"].clip(0, 100).round(1)
        future_only["yhat_upper"] = future_only["yhat_upper"].clip(0, 100).round(1)
        return future_only
    except Exception as e:
        logger.error("Prophet failed for %s: %s", keyword, e)
        return None

def main():
    client = get_supabase()

    logger.info("Fetching India historical data...")
    history_df = fetch_india_history(client)
    logger.info("Fetched %d records", len(history_df))

    keywords_df = fetch_keywords(client)
    kw_lookup = keywords_df.set_index("id")[["keyword", "category"]].to_dict("index")

    history_df["month"] = pd.to_datetime(history_df["month"])
    history_df["keyword_id"] = history_df["keyword_id"].astype(int)

    all_forecasts = []

    for kw_id, kw_info in kw_lookup.items():
        keyword = kw_info["keyword"]
        kw_history = history_df[history_df["keyword_id"] == kw_id][[
            "month", "google_score"
        ]].copy()

        logger.info("Forecasting: %s (%d points)", keyword, len(kw_history))
        forecast = run_forecast(kw_history, keyword)

        if forecast is not None:
            all_forecasts.append(forecast)

    if not all_forecasts:
        logger.error("No forecasts generated")
        return

    combined = pd.concat(all_forecasts, ignore_index=True)

    # Print summary
    print("\n" + "="*70)
    print("12-MONTH FORECAST FOR INDIA")
    print("="*70)

    # Show peak predicted month for each keyword
    summary_rows = []
    for kw, grp in combined.groupby("keyword"):
        best = grp.loc[grp["yhat"].idxmax()]
        summary_rows.append({"keyword": kw, "yhat": best["yhat"], "ds": best["ds"],
                             "yhat_lower": best["yhat_lower"], "yhat_upper": best["yhat_upper"]})
    summary = pd.DataFrame(summary_rows).sort_values("yhat", ascending=False)

    for _, row in summary.iterrows():
        print(f"  {row['keyword']:25s} — peak {row['yhat']:5.1f} in {pd.Timestamp(row['ds']).strftime('%b %Y')} "
              f"(range: {row['yhat_lower']:.0f}-{row['yhat_upper']:.0f})")

    # Save to Supabase
    # Create table first in Supabase:
    # create table if not exists trend_forecasts (
    #   id bigint generated by default as identity primary key,
    #   keyword text not null,
    #   forecast_date date not null,
    #   predicted_score numeric,
    #   lower_bound numeric,
    #   upper_bound numeric,
    #   computed_at date not null default current_date,
    #   constraint trend_forecasts_unique unique (keyword, forecast_date, computed_at)
    # );

    records = []
    for _, row in combined.iterrows():
        records.append({
            "keyword": row["keyword"],
            "forecast_date": row["ds"].date().isoformat(),
            "predicted_score": float(row["yhat"]),
            "lower_bound": float(row["yhat_lower"]),
            "upper_bound": float(row["yhat_upper"]),
            "computed_at": date.today().isoformat(),
        })

    try:
        batch_size = 500
        for i in range(0, len(records), batch_size):
            client.table("trend_forecasts").upsert(
                records[i:i+batch_size],
                on_conflict="keyword,forecast_date,computed_at"
            ).execute()
        logger.info("Saved %d forecast points to Supabase", len(records))
    except Exception as e:
        logger.warning("Could not save to Supabase (create table first): %s", e)
        combined.to_csv(PROJECT_ROOT / "scraper" / "forecasts.csv", index=False)
        logger.info("Saved to forecasts.csv instead")

if __name__ == "__main__":
    main()
