create table if not exists sources (
  id bigint generated by default as identity primary key,
  name text not null unique,
  base_url text,
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists scrape_runs (
  id bigint generated by default as identity primary key,
  source_id bigint not null references sources(id) on delete cascade,
  category_id bigint references categories(id) on delete set null,
  status text not null check (status in ('running', 'completed', 'failed', 'idle')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  products_found integer not null default 0,
  error_message text
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  source_id bigint not null references sources(id) on delete cascade,
  category_id bigint references categories(id) on delete set null,
  title text not null,
  brand text,
  price numeric,
  original_price numeric,
  discount_percentage numeric,
  color text,
  image_url text,
  product_url text not null unique,
  scraped_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists trend_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  category text,
  created_at timestamptz not null default now()
);

create table if not exists trend_snapshots (
  id bigint generated by default as identity primary key,
  keyword_id bigint not null references trend_keywords(id) on delete cascade,
  source_id bigint references sources(id) on delete cascade,
  category_id bigint references categories(id) on delete cascade,
  product_count integer not null default 0,
  snapshot_date date not null,
  previous_count integer,
  growth_percentage numeric,
  status text not null check (status in ('Rising', 'Stable', 'Declining'))
);

create unique index if not exists trend_snapshots_unique_idx
  on trend_snapshots (keyword_id, coalesce(source_id, 0), coalesce(category_id, 0), snapshot_date);

create index if not exists products_source_idx on products (source_id);
create index if not exists products_category_idx on products (category_id);
create index if not exists products_brand_idx on products (brand);
create index if not exists products_color_idx on products (color);
create index if not exists products_scraped_at_idx on products (scraped_at desc);
create index if not exists scrape_runs_started_at_idx on scrape_runs (started_at desc);
create index if not exists trend_snapshots_date_idx on trend_snapshots (snapshot_date desc);
