alter table editorial_articles add column if not exists region text;
alter table editorial_articles add column if not exists visual_prompt text;
alter table editorial_articles add column if not exists content_excerpt text;
alter table editorial_articles add column if not exists full_content text;
alter table editorial_articles add column if not exists source_type text not null default 'original';
alter table editorial_articles add column if not exists image_strategy text not null default 'typography';
alter table editorial_articles alter column cover_image_url drop not null;

alter table micro_documentaries add column if not exists visual_prompt text;
alter table micro_documentaries add column if not exists image_strategy text not null default 'typography';
alter table micro_documentaries alter column thumbnail_url drop not null;

delete from editorial_articles where author in ('Fashion Trend Desk', 'Fashion Trend Editorial');
delete from micro_documentaries where id::text like '33333333-%';

insert into editorial_articles (
  id, title, subtitle, slug, cover_image_url, category, tags, archetypes, reading_time, author,
  published_date, mood, era, region, culture_reference, visual_prompt, content_excerpt, content,
  full_content, source_type, image_strategy, is_featured
) values
('22222222-1001-4222-8222-222222222222','The Sari Is Not an Outfit. It Is a Language.','A drape can be modest, cinematic, sensual, political, ceremonial, or completely modern depending on the body that edits it.','sari-is-a-language',null,'Indian fashion culture',array['sari','drape','heritage'],array['Romantic','Classic','Bohemian'],7,'Fashion Trend Editorial','2026-05-28','intimate','timeless','India','Indian draping traditions, contemporary sari styling','editorial Indian sari fashion drape modern heritage intimate elegant cultural','Why it matters: the sari is not fixed fashion. It lets the wearer decide the silhouette, the mood, and the amount of tradition they want to carry.','Why it matters: the sari is not fixed fashion. It lets the wearer decide the silhouette, the mood, and the amount of tradition they want to carry.','The sari is a language of edit, gesture, memory, and body. This capsule reads the garment as a living system instead of a static outfit.','original','typography',true),
('22222222-1002-4222-8222-222222222222','How 70s Style Made Rebellion Look Soft','Suede, flares, fringe, soft hair, and relaxed shirts turned anti-establishment dressing into a tactile fantasy.','70s-style-soft-rebellion',null,'Fashion history',array['70s fashion','rebellion','bohemian'],array['Bohemian','Romantic','Street Muse'],5,'Fashion Trend Editorial','2026-05-27','free','1970s','Global','Counterculture, disco, festival dressing','vintage 70s runway soft rebellion suede flared denim editorial archive','Why it matters: the 70s taught fashion that resistance does not have to look hard. It can look loose, warm, and wildly personal.','Why it matters: the 70s taught fashion that resistance does not have to look hard. It can look loose, warm, and wildly personal.','Soft rebellion is useful now because people want escape without losing identity. The 70s gives them a proven visual grammar.','original','collage',true),
('22222222-1003-4222-8222-222222222222','Why Romantic Dressing Is Not Weakness','Ribbons, lace, blush, pearls, and drape become powerful when they are styled with tension instead of sweetness alone.','romantic-dressing-not-weakness',null,'Style psychology',array['romantic','coquette','soft power'],array['Romantic','Bohemian'],6,'Fashion Trend Editorial','2026-05-26','dramatic','modern','Global','Coquette styling, balletcore, red-carpet softness','coquette romantic styling pearls ribbons lace cinematic editorial soft power','Why it matters: romantic style is not about looking fragile. It is about using softness as atmosphere, memory, and control.','Why it matters: romantic style is not about looking fragile. It is about using softness as atmosphere, memory, and control.','Romantic dressing gets stronger when it has contrast: lace with denim, pearls with bare skin, softness against structure.','original','gradient',true),
('22222222-1004-4222-8222-222222222222','The Psychology of Wearing Black','Black can disappear, sharpen, protect, seduce, simplify, or make the wearer feel untouchable.','psychology-of-wearing-black',null,'Style psychology',array['black','identity','protection'],array['Minimalist','Avant-Garde','Classic'],6,'Fashion Trend Editorial','2026-05-25','protected','modern','Global','Goth, minimalism, eveningwear, uniform dressing','magazine editorial all black fashion silhouette psychology minimal avant garde','Why it matters: black is rarely neutral. It changes posture, distance, and how much of yourself you choose to reveal.','Why it matters: black is rarely neutral. It changes posture, distance, and how much of yourself you choose to reveal.','Black is a uniform, shield, blank page, and spotlight depending on proportion and texture.','original','typography',true),
('22222222-1005-4222-8222-222222222222','How Old Bollywood Built the Modern Indian Muse','Winged liner, chiffon, bouffants, jewels, silk, and impossible romance still shape how Indian glamour is imagined.','old-bollywood-modern-indian-muse',null,'Indian fashion culture',array['old Bollywood','Indian muse','glamour'],array['Romantic','Classic'],7,'Fashion Trend Editorial','2026-05-24','nostalgic','1960s-1980s','India','Old Bollywood costume, chiffon sari, screen glamour','old Bollywood fashion chiffon sari vintage Indian cinema muse editorial archive','Why it matters: the Indian muse is not just a beauty reference. She is gesture, fabric, jewellery, eye makeup, and controlled drama.','Why it matters: the Indian muse is not just a beauty reference. She is gesture, fabric, jewellery, eye makeup, and controlled drama.','Old Bollywood gave Indian style a cinematic operating system that still powers weddings, reels, editorials, and daily fantasy.','original','collage',true),
('22222222-1006-4222-8222-222222222222','Minimalism Is Not Plain: It Is Controlled Drama','The quieter the outfit, the more proportion, texture, and negative space have to perform.','minimalism-controlled-drama',null,'Personal aesthetic guides',array['minimalism','wardrobe','quiet luxury'],array['Minimalist','Classic'],5,'Fashion Trend Editorial','2026-05-23','quiet','1990s-now','Global','90s minimalism, quiet luxury, capsule wardrobes','minimalist wardrobe editorial clean lines ivory black controlled drama','Why it matters: minimalism only looks expensive when the fit is exact. Otherwise it is just fewer clothes.','Why it matters: minimalism only looks expensive when the fit is exact. Otherwise it is just fewer clothes.','Minimalism is not absence. It is editing until line, cloth, and body become the whole statement.','original','gradient',false),
('22222222-1007-4222-8222-222222222222','Why Gold Jewellery Changes the Whole Face','A hoop, chain, bangle, or jhumka does not just accessorize. It warms the skin and changes the emotional read of the outfit.','gold-jewellery-effect',null,'Styling rituals',array['gold jewellery','Indian styling','face framing'],array['Romantic','Classic','Bohemian'],4,'Fashion Trend Editorial','2026-05-22','glowing','timeless','India','Jhumkas, hoops, bridal jewellery, daily gold','Indian gold jewellery close portrait jhumka editorial warm cinematic','Why it matters: gold can make even a simple white shirt feel inherited, intimate, and intentional.','Why it matters: gold can make even a simple white shirt feel inherited, intimate, and intentional.','Gold changes light around the face. That is why the same outfit can move from plain to ceremonial in one gesture.','original','typography',true),
('22222222-1008-4222-8222-222222222222','The Rise of Soft Power Dressing','Authority is moving away from hard tailoring and toward calm silhouettes that still own the room.','rise-of-soft-power-dressing',null,'Trend intelligence',array['power dressing','tailoring','workwear'],array['Classic','Minimalist','Romantic'],5,'Fashion Trend Editorial','2026-05-21','composed','2020s','Global','Modern workwear, relaxed tailoring, quiet authority','soft power dressing relaxed tailoring women editorial neutral office fashion','Why it matters: people want clothes that signal competence without looking like costume corporate armor.','Why it matters: people want clothes that signal competence without looking like costume corporate armor.','Soft power dressing is the new authority code: low volume, high intention, exact fit, calmer color.','original','gradient',true),
('22222222-1009-4222-8222-222222222222','Coquette, But Make It Indian','Pearls, bows, glass bangles, kajal, lace borders, and tiny cardigans can become local instead of copied.','coquette-but-make-it-indian',null,'Indian fashion culture',array['coquette','Indian romantic','pearls'],array['Romantic','Bohemian'],5,'Fashion Trend Editorial','2026-05-20','sweet but sharp','2020s','India','Coquette trend, Indian jewellery, romantic styling','Indian coquette fashion pearls bangles ribbons romantic editorial styling','Why it matters: global aesthetics become interesting only when they pass through local texture, climate, rituals, and memory.','Why it matters: global aesthetics become interesting only when they pass through local texture, climate, rituals, and memory.','The Indian version of coquette works best when it uses bangles, kajal, anklets, cotton, and soft color instead of copying a Western costume.','original','collage',false),
('22222222-1010-4222-8222-222222222222','Why Denim Became Emotional','Jeans carry rebellion, comfort, memory, attraction, class, and daily repetition in one fabric.','why-denim-became-emotional',null,'Fashion history',array['denim','jeans','workwear'],array['Street Muse','Classic','Bohemian'],5,'Fashion Trend Editorial','2026-05-19','worn-in','1950s-now','Global','Workwear, youth rebellion, Bollywood denim, designer jeans','archival denim fashion worn jeans emotional workwear street style editorial','Why it matters: denim is personal because wash, rise, and fit reveal how the wearer wants to be approached.','Why it matters: denim is personal because wash, rise, and fit reveal how the wearer wants to be approached.','Denim is the rare fabric that can look like labor, sex appeal, comfort, rebellion, and routine.','original','typography',false),
('22222222-1011-4222-8222-222222222222','How Your Clothes Teach People How to Read You','Before you speak, proportion, color, exposure, and polish have already introduced a version of you.','clothes-teach-people-to-read-you',null,'Style psychology',array['identity','first impression','personal style'],array['Classic','Minimalist','Romantic'],6,'Fashion Trend Editorial','2026-05-18','self-aware','modern','Global','Enclothed cognition, social signalling, personal styling','fashion psychology mirror outfit identity editorial cinematic portrait','Why it matters: style is not vanity when it becomes a language for boundary, desire, ambition, and mood.','Why it matters: style is not vanity when it becomes a language for boundary, desire, ambition, and mood.','Every outfit teaches the room something. Good style starts when the lesson becomes intentional.','original','gradient',true),
('22222222-1012-4222-8222-222222222222','The Return of Hair Ribbons, Pearls, and Ritual Dressing','Tiny finishing gestures are coming back because people miss the intimacy of getting ready.','ribbons-pearls-ritual-dressing',null,'Styling rituals',array['hair ribbons','pearls','ritual'],array['Romantic','Classic'],4,'Fashion Trend Editorial','2026-05-17','tender','2020s','Global','Coquette, balletcore, vintage beauty rituals','hair ribbons pearls ritual dressing romantic editorial close details','Why it matters: the smallest accessory often tells the viewer that the outfit was cared for, not merely assembled.','Why it matters: the smallest accessory often tells the viewer that the outfit was cared for, not merely assembled.','Ritual dressing makes style intimate again. The ribbon matters because the gesture matters.','original','typography',false),
('22222222-1013-4222-8222-222222222222','Why Some Outfits Feel Like Protection','Oversized coats, black layers, boots, sunglasses, and sharp shoulders can become emotional armor.','outfits-feel-like-protection',null,'Style psychology',array['protection','armor','silhouette'],array['Avant-Garde','Minimalist','Street Muse'],6,'Fashion Trend Editorial','2026-05-16','guarded','modern','Global','Street style armor, oversized outerwear, urban anonymity','protective fashion oversized coat black layers boots editorial city night','Why it matters: clothing can create distance. Sometimes that distance is the whole point.','Why it matters: clothing can create distance. Sometimes that distance is the whole point.','Protection dressing is style as boundary: big shapes, dark layers, hard shoes, less explanation.','original','gradient',false),
('22222222-1014-4222-8222-222222222222','The Anatomy of a Main Character Wardrobe','A memorable wardrobe needs repeated codes: one silhouette, one color story, one signature object.','main-character-wardrobe',null,'Personal aesthetic guides',array['main character','signature style','wardrobe'],array['Romantic','Classic','Avant-Garde'],5,'Fashion Trend Editorial','2026-05-15','cinematic','modern','Global','Film costume, personal branding, signature dressing','cinematic wardrobe main character fashion editorial closet signature pieces','Why it matters: personal style becomes memorable when people can recognize your codes before reading the label.','Why it matters: personal style becomes memorable when people can recognize your codes before reading the label.','A main character wardrobe is not loud. It is consistent enough to become legible.','original','collage',true),
('22222222-1015-4222-8222-222222222222','How Street Style Became a Diary','The best street style looks less like perfection and more like evidence of a life being lived.','street-style-became-a-diary',null,'Trend intelligence',array['street style','diary','city'],array['Street Muse','Avant-Garde','Bohemian'],5,'Fashion Trend Editorial','2026-05-14','observed','2010s-now','Global','Fashion week street style, city dressing, phone camera culture','street style diary city fashion week candid editorial outfit details','Why it matters: street style works because it feels discovered, not announced.','Why it matters: street style works because it feels discovered, not announced.','The outfit becomes diary when the bag, shoe, crease, and weather feel like evidence of a real day.','original','collage',false),
('22222222-1016-4222-8222-222222222222','Why Texture Matters More Than Trend','Cotton, silk, denim, leather, chiffon, knits, and oxidised metal decide whether an outfit has depth.','texture-matters-more-than-trend',null,'Moodboards',array['texture','fabric','depth'],array['Bohemian','Minimalist','Romantic'],4,'Fashion Trend Editorial','2026-05-13','sensory','timeless','Global','Material culture, fabric shopping, handloom, luxury basics','fashion texture board silk denim cotton oxidised silver tactile editorial','Why it matters: trends tell you what to wear. Texture tells people how the outfit feels.','Why it matters: trends tell you what to wear. Texture tells people how the outfit feels.','Texture is the difference between a flat outfit and a remembered one.','original','typography',false),
('22222222-1017-4222-8222-222222222222','The Difference Between Looking Pretty and Looking Styled','Pretty can be accidental. Styled means the outfit has rhythm, contrast, and a point of view.','pretty-vs-styled',null,'Personal aesthetic guides',array['styling','contrast','outfit formula'],array['Romantic','Classic','Street Muse'],5,'Fashion Trend Editorial','2026-05-12','intentional','modern','Global','Personal styling, editorial styling, outfit analysis','before after fashion styling contrast editorial outfit analysis','Why it matters: the step from pretty to styled is usually one contrast: hard with soft, old with new, polished with undone.','Why it matters: the step from pretty to styled is usually one contrast: hard with soft, old with new, polished with undone.','Styled dressing has rhythm. It gives the eye somewhere to start and somewhere to land.','original','gradient',false),
('22222222-1018-4222-8222-222222222222','How To Build a Wardrobe Around a Feeling','Start with a mood before a product: rain, city, softness, defiance, ceremony, ease.','wardrobe-around-a-feeling',null,'Personal aesthetic guides',array['wardrobe','mood','personal style'],array['Romantic','Bohemian','Minimalist'],6,'Fashion Trend Editorial','2026-05-11','introspective','modern','Global','Mood-first styling, Pinterest boards, capsule wardrobes','wardrobe moodboard feeling based fashion editorial textures colors','Why it matters: a feeling gives the closet direction. Without one, even expensive clothes can look unrelated.','Why it matters: a feeling gives the closet direction. Without one, even expensive clothes can look unrelated.','Mood-first dressing turns shopping into editing. You stop collecting pieces and start building a world.','original','typography',true),
('22222222-1019-4222-8222-222222222222','The Cinema of Everyday Dressing','A scarf on wet hair, a kurta with boots, a shirt half tucked: daily life can hold a frame.','cinema-of-everyday-dressing',null,'Styling rituals',array['everyday dressing','cinema','ritual'],array['Romantic','Street Muse','Classic'],5,'Fashion Trend Editorial','2026-05-10','cinematic','modern','India','City dressing, Indian monsoon, casual styling','cinematic everyday Indian fashion city rain scarf kurta boots editorial','Why it matters: the most wearable style is often not dramatic clothes, but dramatic attention.','Why it matters: the most wearable style is often not dramatic clothes, but dramatic attention.','Everyday dressing becomes cinematic when light, movement, and a single deliberate detail are noticed.','original','collage',false),
('22222222-1020-4222-8222-222222222222','Why Your Pinterest Board Knows You Better Than You Think','Repeated images reveal the self you keep rehearsing: colors, bodies, rooms, fabrics, and futures.','pinterest-board-knows-you',null,'Style psychology',array['Pinterest','style identity','desire'],array['Romantic','Minimalist','Bohemian'],6,'Fashion Trend Editorial','2026-05-09','revealing','2020s','Global','Pinterest moodboards, self curation, aspirational identity','Pinterest fashion moodboard identity collage personal aesthetic editorial','Why it matters: what you save repeatedly is often less about taste and more about the person you are trying to become.','Why it matters: what you save repeatedly is often less about taste and more about the person you are trying to become.','Your board is a pattern machine. It can reveal the silhouettes and moods you keep circling back to.','original','typography',false),
('22222222-1021-4222-8222-222222222222','Archival Runway Is the New Mythology','Vintage runway clips travel because they feel like proof that fashion once made the future visible.','archival-runway-new-mythology',null,'Designer stories',array['archival runway','designer','fashion myth'],array['Avant-Garde','Classic'],5,'Fashion Trend Editorial','2026-05-08','mythic','1990s-2000s','Global','Archival runway, fashion Tumblr, runway video culture','vintage runway archival fashion dramatic silhouettes editorial mythology','Why it matters: archival runway gives people a vocabulary for drama that current algorithms often flatten.','Why it matters: archival runway gives people a vocabulary for drama that current algorithms often flatten.','Archival runway is shared because it feels like a secret from the future that already happened.','original','gradient',false),
('22222222-1022-4222-8222-222222222222','The Indian Blouse Is Having a Main Character Moment','Back details, sleeves, necklines, tie-ups, and embroidery are turning the blouse into the outfit''s thesis.','indian-blouse-main-character',null,'Indian fashion culture',array['blouse','sari','Indian tailoring'],array['Romantic','Avant-Garde','Classic'],5,'Fashion Trend Editorial','2026-05-07','ornate','2020s','India','Contemporary sari blouses, Indian bridal and festive tailoring','Indian blouse design editorial back detail embroidery sari styling','Why it matters: the blouse is where tradition, body confidence, and trend experimentation meet.','Why it matters: the blouse is where tradition, body confidence, and trend experimentation meet.','The blouse now carries silhouette, attitude, and body language. The sari is no longer the only headline.','original','typography',false),
('22222222-1023-4222-8222-222222222222','Why Y2K Came Back Softer','Low-rise chaos returned with baby tees, gloss, denim, metallics, and a little more self-awareness.','y2k-came-back-softer',null,'Trend intelligence',array['Y2K','denim','nostalgia'],array['Street Muse','Romantic'],4,'Fashion Trend Editorial','2026-05-06','glossy','Y2K','Global','2000s pop culture, mall fashion, Instagram revival aesthetics','Y2K fashion baby tee denim gloss street style editorial magazine','Why it matters: Y2K is not just nostalgia. It is a return to visible personality after years of muted minimalism.','Why it matters: Y2K is not just nostalgia. It is a return to visible personality after years of muted minimalism.','The new Y2K is less chaotic and more edited: one glossy cue, one denim cue, one nostalgic proportion.','original','collage',false),
('22222222-1024-4222-8222-222222222222','The Quiet Luxury Lie','Quiet luxury sells restraint, but real style is not quiet unless the wearer wants it to be.','quiet-luxury-lie',null,'Trend intelligence',array['quiet luxury','class','minimalism'],array['Minimalist','Classic','Avant-Garde'],6,'Fashion Trend Editorial','2026-05-05','critical','2020s','Global','Quiet luxury, succession dressing, stealth wealth','quiet luxury neutral wardrobe critical editorial cashmere blazer','Why it matters: the trend often confuses taste with class signals. That difference matters.','Why it matters: the trend often confuses taste with class signals. That difference matters.','Quiet luxury can be useful as an editing tool, but dangerous when it becomes the only accepted image of taste.','original','gradient',false),
('22222222-1025-4222-8222-222222222222','How Shoes Changed Street Style','Sneakers, ballet flats, loafers, boots, and kolhapuris can redirect the entire meaning of a look.','shoes-changed-street-style',null,'Trend intelligence',array['shoes','street style','styling'],array['Street Muse','Classic','Bohemian'],4,'Fashion Trend Editorial','2026-05-04','grounded','2010s-now','Global','Sneaker culture, ballet flat revival, Indian flats','street style shoes sneakers ballet flats boots editorial outfit detail','Why it matters: shoes decide whether the same outfit reads romantic, practical, rebellious, or polished.','Why it matters: shoes decide whether the same outfit reads romantic, practical, rebellious, or polished.','Shoes are the outfit''s final verb. They decide where the look thinks it is going.','original','typography',false),
('22222222-1026-4222-8222-222222222222','The Ritual of Getting Ready','A playlist, mirror, scent, jewellery tray, and last-minute change can be a private form of styling intelligence.','ritual-of-getting-ready',null,'Styling rituals',array['getting ready','ritual','beauty'],array['Romantic','Classic','Bohemian'],5,'Fashion Trend Editorial','2026-05-03','private','timeless','Global','GRWM culture, beauty rituals, dressing tables','getting ready ritual fashion jewellery tray mirror cinematic editorial','Why it matters: style often happens before the outfit appears, in the emotional preparation around it.','Why it matters: style often happens before the outfit appears, in the emotional preparation around it.','The ritual is where taste becomes state of mind: music, scent, touch, edit, exit.','original','collage',false),
('22222222-1027-4222-8222-222222222222','Designer Stories: The Tailor, the Muse, and the Room','Great clothes come from relationships: who is seen, who is shaped, and who is allowed to become more visible.','tailor-muse-room',null,'Designer stories',array['designer','tailoring','muse'],array['Classic','Romantic','Avant-Garde'],7,'Fashion Trend Editorial','2026-05-02','observant','timeless','Global','Atelier culture, tailoring rooms, designer-muse relationships','fashion atelier tailor muse fitting room editorial documentary','Why it matters: clothing is never only product. It is negotiation between body, maker, mood, and room.','Why it matters: clothing is never only product. It is negotiation between body, maker, mood, and room.','Designer stories become human when the room is visible: fittings, pins, hesitation, permission, mirror.','original','typography',false),
('22222222-1028-4222-8222-222222222222','Monsoon Romance, City Edge','Wet pavement, cotton, oxidised silver, dark denim, and silk make rainy dressing feel cinematic.','monsoon-romance-city-edge',null,'Moodboards',array['monsoon','city','romance'],array['Romantic','Street Muse','Bohemian'],4,'Fashion Trend Editorial','2026-05-01','rain-soaked','modern','India','Indian monsoon, city dressing, romantic street style','Indian monsoon fashion city rain wet pavement silk denim oxidised silver editorial','Why it matters: weather can become styling direction instead of an inconvenience.','Why it matters: weather can become styling direction instead of an inconvenience.','Monsoon dressing has its own romance: protected feet, soft cloth, silver, damp hair, practical drama.','original','collage',true),
('22222222-1029-4222-8222-222222222222','How Avant-Garde Silhouettes Teach Courage','A strange sleeve, sculptural skirt, hard shoulder, or asymmetrical hem trains the eye to accept a new self.','avant-garde-silhouettes-teach-courage',null,'Style psychology',array['avant-garde','silhouette','courage'],array['Avant-Garde','Minimalist'],6,'Fashion Trend Editorial','2026-04-30','brave','runway','Global','Japanese designers, Antwerp Six, sculptural runway','avant garde silhouettes sculptural fashion runway editorial black white','Why it matters: wearing an unusual shape is a small practice in being seen before being understood.','Why it matters: wearing an unusual shape is a small practice in being seen before being understood.','Avant-garde dressing is courage training. It lets the wearer leave normal proportions for a while.','original','gradient',false),
('22222222-1030-4222-8222-222222222222','The Wardrobe as a Private Archive','Old shirts, gifted jewellery, travel scarves, and repeated dresses become a record of who you were becoming.','wardrobe-private-archive',null,'Style psychology',array['memory','wardrobe','archive'],array['Romantic','Classic','Bohemian'],6,'Fashion Trend Editorial','2026-04-29','remembering','timeless','Global','Personal archives, heirlooms, sentimental clothing','wardrobe private archive old clothes jewellery memory editorial still life','Why it matters: some clothes are kept because they still know a version of us.','Why it matters: some clothes are kept because they still know a version of us.','A closet is a private archive when the pieces are organized by memory as much as use.','original','typography',false);

insert into micro_documentaries (
  id, title, description, video_url, thumbnail_url, duration_seconds, category, tags, archetypes, visual_prompt, image_strategy
) values
('33333333-1001-4333-8333-333333333333','60 Seconds on the Sari','One drape, infinite identities.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'Indian fashion culture',array['sari','drape'],array['Romantic','Classic','Bohemian'],'vertical film Indian sari drape heritage modern editorial','typography'),
('33333333-1002-4333-8333-333333333333','The Rise of the Indian Romantic Muse','Chiffon, gold, kajal, and soft power.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'culture',array['Indian muse','romantic'],array['Romantic','Classic'],'Indian romantic muse old Bollywood chiffon gold cinematic vertical','collage'),
('33333333-1003-4333-8333-333333333333','Why Black Always Wins','Protection, elegance, rebellion, silence.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'psychology',array['black','identity'],array['Minimalist','Avant-Garde','Classic'],'all black fashion vertical editorial silhouette psychological','gradient'),
('33333333-1004-4333-8333-333333333333','How Y2K Came Back','Gloss, denim, baby tees, and nostalgia.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'trend intelligence',array['Y2K','nostalgia'],array['Street Muse','Romantic'],'Y2K vertical fashion film denim gloss street style','collage'),
('33333333-1005-4333-8333-333333333333','The Gold Jewellery Effect','How one metal changes the face.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'styling rituals',array['gold jewellery','face framing'],array['Romantic','Classic','Bohemian'],'gold jewellery Indian portrait vertical warm cinematic','typography'),
('33333333-1006-4333-8333-333333333333','The Quiet Luxury Lie','When restraint becomes a class signal.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'trend intelligence',array['quiet luxury','minimalism'],array['Minimalist','Classic'],'quiet luxury neutral vertical editorial critical fashion','gradient'),
('33333333-1007-4333-8333-333333333333','Why Old Bollywood Still Dresses Us','The sari, liner, hair, and hand gesture.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'history',array['old Bollywood','Indian cinema'],array['Romantic','Classic'],'old Bollywood fashion vertical archive inspired Indian cinema','collage'),
('33333333-1008-4333-8333-333333333333','How Shoes Changed Street Style','Sneakers, flats, boots, and the outfit''s final verb.','https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4',null,60,'street style',array['shoes','street style'],array['Street Muse','Classic'],'street style shoe details vertical documentary sneakers flats boots','typography');

update style_mood_weekly
set title = 'Monsoon Romance, City Edge',
    description = 'Wet pavement, silk, oxidised silver, cotton, denim, and antique gold. The mood is cinematic, intimate, and a little rebellious.',
    colors = array['#111113','#f3eee7','#9d6474','#b39252','#53687c'],
    textures = array['wet pavement','silk','oxidised silver','cotton','denim'],
    keywords = array['cinematic','intimate','soft rebellion','Indian romantic','city muse'],
    image_board_urls = '{}',
    linked_articles = array['22222222-1028-4222-8222-222222222222'::uuid,'22222222-1001-4222-8222-222222222222'::uuid]
where id = '55555555-5555-4555-8555-555555555555';
