create table if not exists trend_candidates (
  id bigint generated by default as identity primary key,
  phrase text not null,
  normalized_phrase text not null,
  source text,
  source_url text,
  context text,
  category text,
  confidence_score numeric not null default 0,
  evidence_count integer not null default 1,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'promoted')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists trend_candidates_normalized_phrase_idx
  on trend_candidates (normalized_phrase);

create index if not exists trend_candidates_status_idx
  on trend_candidates (status);

create index if not exists trend_candidates_confidence_idx
  on trend_candidates (confidence_score desc);

create index if not exists trend_candidates_last_seen_idx
  on trend_candidates (last_seen_at desc);
