alter table trend_candidates
  add column if not exists source_diversity integer not null default 0,
  add column if not exists growth_velocity numeric not null default 0,
  add column if not exists recency_score numeric not null default 0,
  add column if not exists emergence_stage text not null default 'emerging'
    check (emergence_stage in ('emerging', 'rising', 'peaking', 'mainstream', 'declining')),
  add column if not exists supporting_evidence jsonb not null default '[]'::jsonb,
  add column if not exists last_discovered_at timestamptz;

create index if not exists trend_candidates_emergence_stage_idx
  on trend_candidates (emergence_stage);

create table if not exists trend_candidate_evidence (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references trend_candidates(id) on delete cascade,
  phrase text not null,
  normalized_phrase text not null,
  source_type text not null,
  source_name text,
  source_url text,
  source_key text not null,
  context text,
  evidence_kind text,
  score_contribution numeric not null default 0,
  observed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists trend_candidate_evidence_unique_idx
  on trend_candidate_evidence (candidate_id, source_key);

create index if not exists trend_candidate_evidence_phrase_idx
  on trend_candidate_evidence (normalized_phrase);

create index if not exists trend_candidate_evidence_source_type_idx
  on trend_candidate_evidence (source_type);

create index if not exists trend_candidate_evidence_observed_at_idx
  on trend_candidate_evidence (observed_at desc);
