create table if not exists trend_outfit_assets (
  id bigint generated by default as identity primary key,
  trend_keyword text not null,
  normalized_trend_keyword text not null,
  asset_context text not null default 'trend-card',
  audience text not null default 'neutral',
  outfit_formula text not null,
  outfit_title text not null,
  image_url text not null,
  image_source text not null check (image_source in ('ollama', 'pexels', 'product_catalog', 'look_library', 'fallback')),
  prompt text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table trend_outfit_assets
  add column if not exists asset_context text not null default 'trend-card',
  add column if not exists audience text not null default 'neutral';

drop index if exists trend_outfit_assets_keyword_formula_uidx;

create unique index if not exists trend_outfit_assets_context_audience_formula_uidx
  on trend_outfit_assets (normalized_trend_keyword, asset_context, audience, outfit_formula);

create index if not exists trend_outfit_assets_status_idx
  on trend_outfit_assets (status);

create index if not exists trend_outfit_assets_keyword_status_idx
  on trend_outfit_assets (normalized_trend_keyword, status);

create index if not exists trend_outfit_assets_context_audience_idx
  on trend_outfit_assets (normalized_trend_keyword, asset_context, audience);
