create extension if not exists pgcrypto;

create table if not exists trend_keyword_aliases (
  id bigint generated by default as identity primary key,
  raw_keyword text not null,
  canonical_keyword text not null,
  mapping_type text not null default 'self'
    check (mapping_type in ('self', 'format_alias', 'explicit_synonym', 'translated_alias')),
  mapping_confidence numeric not null default 1
    check (mapping_confidence >= 0 and mapping_confidence <= 1),
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists trend_keyword_aliases_raw_keyword_idx
  on trend_keyword_aliases (raw_keyword);

create index if not exists trend_keyword_aliases_canonical_keyword_idx
  on trend_keyword_aliases (canonical_keyword);

create table if not exists regional_trend_scores (
  id bigint generated by default as identity primary key,
  canonical_keyword text not null,
  raw_keywords text[] not null default '{}',
  region text not null,
  latest_period date not null,
  current_interest_percentile numeric not null default 0,
  velocity_percentile numeric not null default 0,
  acceleration_percentile numeric not null default 0,
  positive_period_persistence numeric not null default 0,
  negative_period_persistence numeric not null default 0,
  regional_rank integer,
  observation_count integer not null default 0,
  data_freshness numeric not null default 0,
  regional_momentum numeric not null default 0,
  confidence numeric not null default 0,
  computation_version text not null,
  computed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists regional_trend_scores_unique_idx
  on regional_trend_scores (canonical_keyword, region, latest_period, computation_version);

create index if not exists regional_trend_scores_region_idx
  on regional_trend_scores (region, computed_at desc);

create index if not exists regional_trend_scores_keyword_idx
  on regional_trend_scores (canonical_keyword, computed_at desc);

create table if not exists global_trend_scores (
  id bigint generated by default as identity primary key,
  canonical_keyword text not null,
  primary_keyword_id bigint references trend_keywords(id) on delete set null,
  raw_keywords text[] not null default '{}',
  editorial_display_name text not null,
  lifecycle text not null
    check (lifecycle in ('RISING', 'PEAKING', 'FADING', 'STABLE', 'INSUFFICIENT_DATA')),
  market_classification text not null
    check (market_classification in (
      'india_breakout',
      'cross_market_rising',
      'coming_to_india',
      'global_momentum',
      'local_only',
      'insufficient_evidence'
    )),
  india_momentum numeric,
  cross_region_momentum numeric not null default 0,
  region_breadth numeric not null default 0,
  regions_observed text[] not null default '{}',
  regions_rising text[] not null default '{}',
  regions_fading text[] not null default '{}',
  lead_regions text[] not null default '{}',
  fashion_lead_market_momentum numeric not null default 0,
  source_diversity integer not null default 0,
  persistence numeric not null default 0,
  confidence numeric not null default 0,
  final_trend_score numeric not null default 0,
  latest_period date,
  evidence_hash text,
  evidence_summary jsonb not null default '{}'::jsonb,
  computation_version text not null,
  computed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists global_trend_scores_unique_idx
  on global_trend_scores (canonical_keyword, computation_version);

create index if not exists global_trend_scores_lifecycle_idx
  on global_trend_scores (lifecycle, final_trend_score desc);

create index if not exists global_trend_scores_computed_idx
  on global_trend_scores (computed_at desc, final_trend_score desc);

create index if not exists global_trend_scores_display_name_idx
  on global_trend_scores using gin (to_tsvector('simple', editorial_display_name || ' ' || canonical_keyword));

create table if not exists trend_editorial_names (
  id bigint generated by default as identity primary key,
  canonical_keyword text not null,
  editorial_display_name text not null,
  evidence_hash text not null,
  evidence_summary jsonb not null default '{}'::jsonb,
  ai_confidence numeric not null default 0
    check (ai_confidence >= 0 and ai_confidence <= 1),
  model_config_version text not null,
  used_facets text[] not null default '{}',
  rationale text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists trend_editorial_names_unique_idx
  on trend_editorial_names (canonical_keyword, evidence_hash);

create index if not exists trend_editorial_names_keyword_idx
  on trend_editorial_names (canonical_keyword, updated_at desc);

create table if not exists trend_pipeline_runs (
  id uuid primary key default gen_random_uuid(),
  computation_version text not null,
  status text not null check (status in ('running', 'completed', 'failed')),
  dry_run boolean not null default true,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  rows_read integer not null default 0,
  regional_scores integer not null default 0,
  global_scores integer not null default 0,
  ai_attempts integer not null default 0,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists trend_pipeline_runs_started_idx
  on trend_pipeline_runs (started_at desc);

alter table trend_keyword_aliases enable row level security;
alter table regional_trend_scores enable row level security;
alter table global_trend_scores enable row level security;
alter table trend_editorial_names enable row level security;
alter table trend_pipeline_runs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'trend_keyword_aliases' and policyname = 'trend keyword aliases are readable'
  ) then
    create policy "trend keyword aliases are readable"
      on trend_keyword_aliases for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'regional_trend_scores' and policyname = 'regional trend scores are readable'
  ) then
    create policy "regional trend scores are readable"
      on regional_trend_scores for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'global_trend_scores' and policyname = 'global trend scores are readable'
  ) then
    create policy "global trend scores are readable"
      on global_trend_scores for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'trend_editorial_names' and policyname = 'trend editorial names are readable'
  ) then
    create policy "trend editorial names are readable"
      on trend_editorial_names for select
      using (true);
  end if;
end $$;
