alter table historical_trend_data
  add column if not exists period_status text not null default 'complete'
    check (period_status in ('partial', 'complete')),
  add column if not exists period_finalized_at timestamptz,
  add column if not exists provider_finalized_at timestamptz,
  add column if not exists ingestion_run_id uuid;

create unique index if not exists historical_trend_data_keyword_month_market_unique_idx
  on historical_trend_data (keyword_id, month, market);

create index if not exists historical_trend_data_period_status_idx
  on historical_trend_data (market, month, period_status);

create table if not exists trend_period_region_status (
  id bigint generated by default as identity primary key,
  region text not null,
  period_month date not null,
  period_status text not null
    check (period_status in ('partial', 'complete', 'provider_not_ready', 'failed')),
  expected_period_end date not null,
  provider_ready boolean not null default false,
  row_count integer not null default 0,
  keyword_count integer not null default 0,
  attempted_at timestamptz not null default now(),
  finalized_at timestamptz,
  retry_after timestamptz,
  error_message text,
  computation_version text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists trend_period_region_status_unique_idx
  on trend_period_region_status (region, period_month);

create index if not exists trend_period_region_status_status_idx
  on trend_period_region_status (period_status, period_month desc);

create table if not exists trend_global_period_status (
  id bigint generated by default as identity primary key,
  period_month date not null unique,
  period_status text not null
    check (period_status in ('partial', 'complete', 'incomplete')),
  expected_regions text[] not null default '{}',
  complete_regions text[] not null default '{}',
  missing_regions text[] not null default '{}',
  material_coverage_ratio numeric not null default 0,
  is_materially_complete boolean not null default false,
  computed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists trend_global_period_status_period_idx
  on trend_global_period_status (period_month desc, period_status);

alter table trend_period_region_status enable row level security;
alter table trend_global_period_status enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'trend_period_region_status' and policyname = 'trend period region status is readable'
  ) then
    create policy "trend period region status is readable"
      on trend_period_region_status for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'trend_global_period_status' and policyname = 'trend global period status is readable'
  ) then
    create policy "trend global period status is readable"
      on trend_global_period_status for select
      using (true);
  end if;
end $$;
