import type {
  EditorialArticle,
  HeroVideo,
  MicroDocumentary,
  StyleMoodWeekly,
  StyleQuizQuestion,
} from "@/lib/discover-editorial";

const author = "Fashion Trend Editorial";

function makeArticle(input: Omit<EditorialArticle, "author" | "published_date" | "content" | "full_content" | "source_type"> & {
  date: string;
  content_excerpt: string;
  full_content?: string;
  source_type?: EditorialArticle["source_type"];
}): EditorialArticle {
  const { date, full_content, source_type, ...article } = input;
  return {
    ...article,
    author,
    published_date: `${date}T00:00:00.000Z`,
    content: input.content_excerpt,
    full_content:
      full_content ??
      `${input.content_excerpt} This piece is written as an editorial capsule: what the look signals, why the mood is returning, and how a person can translate it into their own wardrobe without copying the reference too literally.`,
    source_type: source_type ?? "original",
  };
}

export const seedHero: HeroVideo = {
  id: "11111111-1111-4111-8111-111111111111",
  title: "Enter the world of style before it becomes obvious.",
  subtitle:
    "A cinematic discover page for fashion history, style psychology, Indian culture, moodboards, and the signals shaping what people want to become.",
  video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
  poster_image_url:
    "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1800&q=85",
  cta_text: "Find your style world",
  cta_link: "#style-quiz",
  is_active: true,
  active_from: "2026-05-28T00:00:00.000Z",
  active_to: null,
};

export const seedArticles: EditorialArticle[] = [
  makeArticle({
    id: "22222222-1001-4222-8222-222222222222",
    title: "The Sari Is Not an Outfit. It Is a Language.",
    subtitle: "A drape can be modest, cinematic, sensual, political, ceremonial, or completely modern depending on the body that edits it.",
    slug: "sari-is-a-language",
    cover_image_url: null,
    category: "Indian fashion culture",
    tags: ["sari", "drape", "heritage"],
    archetypes: ["Romantic", "Classic", "Bohemian"],
    reading_time: 7,
    date: "2026-05-28",
    mood: "intimate",
    era: "timeless",
    region: "India",
    culture_reference: "Indian draping traditions, contemporary sari styling",
    visual_prompt: "editorial Indian sari fashion drape modern heritage intimate elegant cultural",
    content_excerpt: "Why it matters: the sari is not fixed fashion. It lets the wearer decide the silhouette, the mood, and the amount of tradition they want to carry.",
    full_content:
      "The sari begins as a rectangle, but it never stays neutral. The moment it meets a body, it becomes decision: how low the pleats sit, how much shoulder is shown, whether the pallu is pinned into discipline or left to move like weather. That is why calling it an outfit feels too small. It is closer to a language, one that can speak ceremony, rebellion, modesty, sensuality, memory, or modern ease without changing its basic form. In India, few garments hold this much authorship.\n\nWhat makes the sari powerful is that it refuses to be finished by the designer alone. The wearer completes it. A cotton sari with silver jewellery can feel intellectual and spare; chiffon with kajal and loose hair can become pure cinema; a sharp blouse can pull the same drape into the present. The sari survives trend cycles because it is not one silhouette. It is a system for creating silhouettes.\n\nThis matters now because younger dressers are no longer treating heritage as a costume box. They are wearing saris with sneakers, corset blouses, wet hair, work bags, boots, oversized shirts, and bare backs. Some versions are imperfect. Some are brilliant. But the shift is important: the sari is not being preserved behind glass. It is being edited in public.\n\nTo wear a sari well today is not to copy one correct tradition. It is to understand what part of tradition you want to carry and what part of yourself you want to reveal. That tension is where the garment becomes alive.",
    image_strategy: "typography",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1002-4222-8222-222222222222",
    title: "How 70s Style Made Rebellion Look Soft",
    subtitle: "Suede, flares, fringe, soft hair, and relaxed shirts turned anti-establishment dressing into a tactile fantasy.",
    slug: "70s-style-soft-rebellion",
    cover_image_url: null,
    category: "Fashion history",
    tags: ["70s fashion", "rebellion", "bohemian"],
    archetypes: ["Bohemian", "Romantic", "Street Muse"],
    reading_time: 5,
    date: "2026-05-27",
    mood: "free",
    era: "1970s",
    region: "Global",
    culture_reference: "Counterculture, disco, festival dressing",
    visual_prompt: "vintage 70s runway soft rebellion suede flared denim editorial archive",
    content_excerpt: "Why it matters: the 70s taught fashion that resistance does not have to look hard. It can look loose, warm, and wildly personal.",
    full_content:
      "The 70s did not make rebellion look like armor. It made rebellion look tactile. Suede jackets, flared denim, loose shirts, crochet, fringe, round sunglasses, and undone hair created a softer kind of refusal, one that pushed against stiffness without losing romance. The clothes looked lived in before they were even worn. They had movement, dust, sunlight, and music built into them.\n\nThat is why the decade keeps returning whenever fashion feels too polished. The 70s offer a fantasy of escape, but not the cold kind. It is rebellion with warmth: a shirt open at the throat, denim that changes shape with the body, boots that look like they have crossed a city, jewellery that feels collected instead of purchased. Even disco shine had softness because it belonged to movement rather than perfection.\n\nThe lesson is useful now. People want individuality, but they do not always want aggression. A 70s reference can make an outfit feel personal without making it feel overdesigned. One flare, one suede texture, one warm lens, one soft printed blouse can loosen the entire mood of a wardrobe.\n\nThe trick is not to dress like a costume from the decade. The trick is to borrow its emotional logic. Let the clothes breathe. Let the silhouette move. Let rebellion look like ease.",
    image_strategy: "collage",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1003-4222-8222-222222222222",
    title: "Why Romantic Dressing Is Not Weakness",
    subtitle: "Ribbons, lace, blush, pearls, and drape become powerful when they are styled with tension instead of sweetness alone.",
    slug: "romantic-dressing-not-weakness",
    cover_image_url: null,
    category: "Style psychology",
    tags: ["romantic", "coquette", "soft power"],
    archetypes: ["Romantic", "Bohemian"],
    reading_time: 6,
    date: "2026-05-26",
    mood: "dramatic",
    era: "modern",
    region: "Global",
    culture_reference: "Coquette styling, balletcore, red-carpet softness",
    visual_prompt: "coquette romantic styling pearls ribbons lace cinematic editorial soft power",
    content_excerpt: "Why it matters: romantic style is not about looking fragile. It is about using softness as atmosphere, memory, and control.",
    full_content:
      "Romantic dressing is often misunderstood because people confuse softness with weakness. A ribbon, a pearl, a lace edge, a blush dress, or a sheer sleeve can look delicate, but delicacy is not the same as surrender. In styling, softness can be extremely controlled. It decides where the eye rests. It creates atmosphere. It makes the wearer feel remembered.\n\nThe strongest romantic outfits usually contain tension. Lace becomes more interesting next to denim. Pearls look sharper against bare skin or a plain black knit. A bow feels less childish when the rest of the outfit is severe. This is why romantic dressing works best when it is not trying to be sweet all over. It needs one thing that interrupts the sweetness.\n\nFor Indian styling, romance has even more texture to work with: glass bangles, kajal, anklets, jasmine, chiffon, embroidered borders, soft cotton, gold, and hair left slightly undone. The romantic mood does not have to be imported whole from a Western aesthetic. It can become local, warmer, more intimate, and more lived in.\n\nRomantic dressing is powerful because it lets a person choose feeling as a visible style code. Not everything has to look efficient to be intelligent. Sometimes the most modern thing an outfit can do is make tenderness look deliberate.",
    image_strategy: "gradient",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1004-4222-8222-222222222222",
    title: "The Psychology of Wearing Black",
    subtitle: "Black can disappear, sharpen, protect, seduce, simplify, or make the wearer feel untouchable.",
    slug: "psychology-of-wearing-black",
    cover_image_url: null,
    category: "Style psychology",
    tags: ["black", "identity", "protection"],
    archetypes: ["Minimalist", "Avant-Garde", "Classic"],
    reading_time: 6,
    date: "2026-05-25",
    mood: "protected",
    era: "modern",
    region: "Global",
    culture_reference: "Goth, minimalism, eveningwear, uniform dressing",
    visual_prompt: "magazine editorial all black fashion silhouette psychology minimal avant garde",
    content_excerpt: "Why it matters: black is rarely neutral. It changes posture, distance, and how much of yourself you choose to reveal.",
    full_content:
      "Black is the easiest color to wear and one of the hardest to read. It can be invisibility, elegance, protection, seduction, grief, discipline, rebellion, or boredom depending on the person inside it. That is why black is never just black. The meaning changes with fabric, skin, silhouette, and the amount of body the outfit allows into the room.\n\nA black slip dress does not say the same thing as a black oversized coat. A black turtleneck does not speak like black leather boots. Matte black absorbs attention; satin black reflects it. Sheer black reveals while pretending to conceal. The psychology of the color lives in these differences. It lets the wearer control distance: come closer, stay away, look at the shape, do not ask too much.\n\nFor minimalists, black can simplify the world. For avant-garde dressers, it can make unusual shapes easier to accept. For classic dressers, it can create instant polish. The danger is laziness: black can hide a weak outfit as easily as it can sharpen a strong one.\n\nThe best black outfits have texture and proportion. They know whether they are trying to disappear or dominate. When black works, it gives the wearer a border. Sometimes that border is the whole point.",
    image_strategy: "typography",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1005-4222-8222-222222222222",
    title: "How Old Bollywood Built the Modern Indian Muse",
    subtitle: "Winged liner, chiffon, bouffants, jewels, silk, and impossible romance still shape how Indian glamour is imagined.",
    slug: "old-bollywood-modern-indian-muse",
    cover_image_url: null,
    category: "Indian fashion culture",
    tags: ["old Bollywood", "Indian muse", "glamour"],
    archetypes: ["Romantic", "Classic"],
    reading_time: 7,
    date: "2026-05-24",
    mood: "nostalgic",
    era: "1960s-1980s",
    region: "India",
    culture_reference: "Old Bollywood costume, chiffon sari, screen glamour",
    visual_prompt: "old Bollywood fashion chiffon sari vintage Indian cinema muse editorial archive",
    content_excerpt: "Why it matters: the Indian muse is not just a beauty reference. She is gesture, fabric, jewellery, eye makeup, and controlled drama.",
    full_content:
      "Old Bollywood did not simply dress women beautifully. It taught generations how glamour could move. A chiffon sari in the wind, a sharp wing of liner, a bouffant held in place, a hand lifting to adjust an earring, a song sequence built around longing - these images became part of the Indian style imagination. They were not just costumes. They were emotional instructions.\n\nThe modern Indian muse still borrows from that grammar. She understands that fabric is only one part of the image. Gesture matters. Hair matters. The pause before speaking matters. Gold at the ear, kajal around the eye, a sari caught by light, a blouse cut with confidence - these details turn clothing into cinema.\n\nWhat is interesting now is that old Bollywood references are no longer trapped in nostalgia. They are being remixed with jeans, tank tops, wet hair, minimal sandals, oversized shirts, and sharper makeup. The romance stays, but the woman wearing it feels less distant. She is not only being looked at. She is directing the scene.\n\nThat is the real inheritance of old Bollywood style: not chiffon alone, not jewellery alone, but the belief that getting dressed can create a character. The muse is modern when she controls the frame.",
    image_strategy: "collage",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1006-4222-8222-222222222222",
    title: "Minimalism Is Not Plain: It Is Controlled Drama",
    subtitle: "The quieter the outfit, the more proportion, texture, and negative space have to perform.",
    slug: "minimalism-controlled-drama",
    cover_image_url: null,
    category: "Personal aesthetic guides",
    tags: ["minimalism", "wardrobe", "quiet luxury"],
    archetypes: ["Minimalist", "Classic"],
    reading_time: 5,
    date: "2026-05-23",
    mood: "quiet",
    era: "1990s-now",
    region: "Global",
    culture_reference: "90s minimalism, quiet luxury, capsule wardrobes",
    visual_prompt: "minimalist wardrobe editorial clean lines ivory black controlled drama",
    content_excerpt: "Why it matters: minimalism only looks expensive when the fit is exact. Otherwise it is just fewer clothes.",
    image_strategy: "gradient",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1007-4222-8222-222222222222",
    title: "Why Gold Jewellery Changes the Whole Face",
    subtitle: "A hoop, chain, bangle, or jhumka does not just accessorize. It warms the skin and changes the emotional read of the outfit.",
    slug: "gold-jewellery-effect",
    cover_image_url: null,
    category: "Styling rituals",
    tags: ["gold jewellery", "Indian styling", "face framing"],
    archetypes: ["Romantic", "Classic", "Bohemian"],
    reading_time: 4,
    date: "2026-05-22",
    mood: "glowing",
    era: "timeless",
    region: "India",
    culture_reference: "Jhumkas, hoops, bridal jewellery, daily gold",
    visual_prompt: "Indian gold jewellery close portrait jhumka editorial warm cinematic",
    content_excerpt: "Why it matters: gold can make even a simple white shirt feel inherited, intimate, and intentional.",
    full_content:
      "Gold jewellery changes an outfit before anyone notices the clothes. It warms the face, catches light near the skin, and gives even the plainest look a sense of memory. A white shirt with bare ears can feel clean; the same shirt with hoops or jhumkas can feel intimate, inherited, and complete. Gold does not simply decorate. It changes the temperature of the image.\n\nIn Indian dressing, gold carries more than shine. It carries ceremony, family, religion, weddings, daily habit, and the quiet confidence of women who put on earrings before stepping out of the house. That emotional history is why a small chain or bangle can feel more powerful than a trend piece. It suggests continuity.\n\nThe styling lesson is simple: gold works best when it has a relationship with the face. Earrings lift attention. A chain softens the neckline. Bangles add sound and movement. A ring can make the hand part of the outfit. The effect is strongest when the clothes leave enough room for the metal to speak.\n\nGold is not always about luxury. Sometimes it is about warmth. Sometimes it is about looking like you belong to yourself before you belong to the room.",
    image_strategy: "typography",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1008-4222-8222-222222222222",
    title: "The Rise of Soft Power Dressing",
    subtitle: "Authority is moving away from hard tailoring and toward calm silhouettes that still own the room.",
    slug: "rise-of-soft-power-dressing",
    cover_image_url: null,
    category: "Trend intelligence",
    tags: ["power dressing", "tailoring", "workwear"],
    archetypes: ["Classic", "Minimalist", "Romantic"],
    reading_time: 5,
    date: "2026-05-21",
    mood: "composed",
    era: "2020s",
    region: "Global",
    culture_reference: "Modern workwear, relaxed tailoring, quiet authority",
    visual_prompt: "soft power dressing relaxed tailoring women editorial neutral office fashion",
    content_excerpt: "Why it matters: people want clothes that signal competence without looking like costume corporate armor.",
    image_strategy: "gradient",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1009-4222-8222-222222222222",
    title: "Coquette, But Make It Indian",
    subtitle: "Pearls, bows, glass bangles, kajal, lace borders, and tiny cardigans can become local instead of copied.",
    slug: "coquette-but-make-it-indian",
    cover_image_url: null,
    category: "Indian fashion culture",
    tags: ["coquette", "Indian romantic", "pearls"],
    archetypes: ["Romantic", "Bohemian"],
    reading_time: 5,
    date: "2026-05-20",
    mood: "sweet but sharp",
    era: "2020s",
    region: "India",
    culture_reference: "Coquette trend, Indian jewellery, romantic styling",
    visual_prompt: "Indian coquette fashion pearls bangles ribbons romantic editorial styling",
    content_excerpt: "Why it matters: global aesthetics become interesting only when they pass through local texture, climate, rituals, and memory.",
    image_strategy: "collage",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1010-4222-8222-222222222222",
    title: "Why Denim Became Emotional",
    subtitle: "Jeans carry rebellion, comfort, memory, attraction, class, and daily repetition in one fabric.",
    slug: "why-denim-became-emotional",
    cover_image_url: null,
    category: "Fashion history",
    tags: ["denim", "jeans", "workwear"],
    archetypes: ["Street Muse", "Classic", "Bohemian"],
    reading_time: 5,
    date: "2026-05-19",
    mood: "worn-in",
    era: "1950s-now",
    region: "Global",
    culture_reference: "Workwear, youth rebellion, Bollywood denim, designer jeans",
    visual_prompt: "archival denim fashion worn jeans emotional workwear street style editorial",
    content_excerpt: "Why it matters: denim is personal because wash, rise, and fit reveal how the wearer wants to be approached.",
    image_strategy: "typography",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1011-4222-8222-222222222222",
    title: "How Your Clothes Teach People How to Read You",
    subtitle: "Before you speak, proportion, color, exposure, and polish have already introduced a version of you.",
    slug: "clothes-teach-people-to-read-you",
    cover_image_url: null,
    category: "Style psychology",
    tags: ["identity", "first impression", "personal style"],
    archetypes: ["Classic", "Minimalist", "Romantic"],
    reading_time: 6,
    date: "2026-05-18",
    mood: "self-aware",
    era: "modern",
    region: "Global",
    culture_reference: "Enclothed cognition, social signalling, personal styling",
    visual_prompt: "fashion psychology mirror outfit identity editorial cinematic portrait",
    content_excerpt: "Why it matters: style is not vanity when it becomes a language for boundary, desire, ambition, and mood.",
    image_strategy: "gradient",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1012-4222-8222-222222222222",
    title: "The Return of Hair Ribbons, Pearls, and Ritual Dressing",
    subtitle: "Tiny finishing gestures are coming back because people miss the intimacy of getting ready.",
    slug: "ribbons-pearls-ritual-dressing",
    cover_image_url: null,
    category: "Styling rituals",
    tags: ["hair ribbons", "pearls", "ritual"],
    archetypes: ["Romantic", "Classic"],
    reading_time: 4,
    date: "2026-05-17",
    mood: "tender",
    era: "2020s",
    region: "Global",
    culture_reference: "Coquette, balletcore, vintage beauty rituals",
    visual_prompt: "hair ribbons pearls ritual dressing romantic editorial close details",
    content_excerpt: "Why it matters: the smallest accessory often tells the viewer that the outfit was cared for, not merely assembled.",
    image_strategy: "typography",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1013-4222-8222-222222222222",
    title: "Why Some Outfits Feel Like Protection",
    subtitle: "Oversized coats, black layers, boots, sunglasses, and sharp shoulders can become emotional armor.",
    slug: "outfits-feel-like-protection",
    cover_image_url: null,
    category: "Style psychology",
    tags: ["protection", "armor", "silhouette"],
    archetypes: ["Avant-Garde", "Minimalist", "Street Muse"],
    reading_time: 6,
    date: "2026-05-16",
    mood: "guarded",
    era: "modern",
    region: "Global",
    culture_reference: "Street style armor, oversized outerwear, urban anonymity",
    visual_prompt: "protective fashion oversized coat black layers boots editorial city night",
    content_excerpt: "Why it matters: clothing can create distance. Sometimes that distance is the whole point.",
    image_strategy: "gradient",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1014-4222-8222-222222222222",
    title: "The Anatomy of a Main Character Wardrobe",
    subtitle: "A memorable wardrobe needs repeated codes: one silhouette, one color story, one signature object.",
    slug: "main-character-wardrobe",
    cover_image_url: null,
    category: "Personal aesthetic guides",
    tags: ["main character", "signature style", "wardrobe"],
    archetypes: ["Romantic", "Classic", "Avant-Garde"],
    reading_time: 5,
    date: "2026-05-15",
    mood: "cinematic",
    era: "modern",
    region: "Global",
    culture_reference: "Film costume, personal branding, signature dressing",
    visual_prompt: "cinematic wardrobe main character fashion editorial closet signature pieces",
    content_excerpt: "Why it matters: personal style becomes memorable when people can recognize your codes before reading the label.",
    image_strategy: "collage",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1015-4222-8222-222222222222",
    title: "How Street Style Became a Diary",
    subtitle: "The best street style looks less like perfection and more like evidence of a life being lived.",
    slug: "street-style-became-a-diary",
    cover_image_url: null,
    category: "Trend intelligence",
    tags: ["street style", "diary", "city"],
    archetypes: ["Street Muse", "Avant-Garde", "Bohemian"],
    reading_time: 5,
    date: "2026-05-14",
    mood: "observed",
    era: "2010s-now",
    region: "Global",
    culture_reference: "Fashion week street style, city dressing, phone camera culture",
    visual_prompt: "street style diary city fashion week candid editorial outfit details",
    content_excerpt: "Why it matters: street style works because it feels discovered, not announced.",
    image_strategy: "collage",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1016-4222-8222-222222222222",
    title: "Why Texture Matters More Than Trend",
    subtitle: "Cotton, silk, denim, leather, chiffon, knits, and oxidised metal decide whether an outfit has depth.",
    slug: "texture-matters-more-than-trend",
    cover_image_url: null,
    category: "Moodboards",
    tags: ["texture", "fabric", "depth"],
    archetypes: ["Bohemian", "Minimalist", "Romantic"],
    reading_time: 4,
    date: "2026-05-13",
    mood: "sensory",
    era: "timeless",
    region: "Global",
    culture_reference: "Material culture, fabric shopping, handloom, luxury basics",
    visual_prompt: "fashion texture board silk denim cotton oxidised silver tactile editorial",
    content_excerpt: "Why it matters: trends tell you what to wear. Texture tells people how the outfit feels.",
    image_strategy: "typography",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1017-4222-8222-222222222222",
    title: "The Difference Between Looking Pretty and Looking Styled",
    subtitle: "Pretty can be accidental. Styled means the outfit has rhythm, contrast, and a point of view.",
    slug: "pretty-vs-styled",
    cover_image_url: null,
    category: "Personal aesthetic guides",
    tags: ["styling", "contrast", "outfit formula"],
    archetypes: ["Romantic", "Classic", "Street Muse"],
    reading_time: 5,
    date: "2026-05-12",
    mood: "intentional",
    era: "modern",
    region: "Global",
    culture_reference: "Personal styling, editorial styling, outfit analysis",
    visual_prompt: "before after fashion styling contrast editorial outfit analysis",
    content_excerpt: "Why it matters: the step from pretty to styled is usually one contrast: hard with soft, old with new, polished with undone.",
    image_strategy: "gradient",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1018-4222-8222-222222222222",
    title: "How To Build a Wardrobe Around a Feeling",
    subtitle: "Start with a mood before a product: rain, city, softness, defiance, ceremony, ease.",
    slug: "wardrobe-around-a-feeling",
    cover_image_url: null,
    category: "Personal aesthetic guides",
    tags: ["wardrobe", "mood", "personal style"],
    archetypes: ["Romantic", "Bohemian", "Minimalist"],
    reading_time: 6,
    date: "2026-05-11",
    mood: "introspective",
    era: "modern",
    region: "Global",
    culture_reference: "Mood-first styling, Pinterest boards, capsule wardrobes",
    visual_prompt: "wardrobe moodboard feeling based fashion editorial textures colors",
    content_excerpt: "Why it matters: a feeling gives the closet direction. Without one, even expensive clothes can look unrelated.",
    image_strategy: "typography",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1019-4222-8222-222222222222",
    title: "The Cinema of Everyday Dressing",
    subtitle: "A scarf on wet hair, a kurta with boots, a shirt half tucked: daily life can hold a frame.",
    slug: "cinema-of-everyday-dressing",
    cover_image_url: null,
    category: "Styling rituals",
    tags: ["everyday dressing", "cinema", "ritual"],
    archetypes: ["Romantic", "Street Muse", "Classic"],
    reading_time: 5,
    date: "2026-05-10",
    mood: "cinematic",
    era: "modern",
    region: "India",
    culture_reference: "City dressing, Indian monsoon, casual styling",
    visual_prompt: "cinematic everyday Indian fashion city rain scarf kurta boots editorial",
    content_excerpt: "Why it matters: the most wearable style is often not dramatic clothes, but dramatic attention.",
    image_strategy: "collage",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1020-4222-8222-222222222222",
    title: "Why Your Pinterest Board Knows You Better Than You Think",
    subtitle: "Repeated images reveal the self you keep rehearsing: colors, bodies, rooms, fabrics, and futures.",
    slug: "pinterest-board-knows-you",
    cover_image_url: null,
    category: "Style psychology",
    tags: ["Pinterest", "style identity", "desire"],
    archetypes: ["Romantic", "Minimalist", "Bohemian"],
    reading_time: 6,
    date: "2026-05-09",
    mood: "revealing",
    era: "2020s",
    region: "Global",
    culture_reference: "Pinterest moodboards, self curation, aspirational identity",
    visual_prompt: "Pinterest fashion moodboard identity collage personal aesthetic editorial",
    content_excerpt: "Why it matters: what you save repeatedly is often less about taste and more about the person you are trying to become.",
    image_strategy: "typography",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1021-4222-8222-222222222222",
    title: "Archival Runway Is the New Mythology",
    subtitle: "Vintage runway clips travel because they feel like proof that fashion once made the future visible.",
    slug: "archival-runway-new-mythology",
    cover_image_url: null,
    category: "Designer stories",
    tags: ["archival runway", "designer", "fashion myth"],
    archetypes: ["Avant-Garde", "Classic"],
    reading_time: 5,
    date: "2026-05-08",
    mood: "mythic",
    era: "1990s-2000s",
    region: "Global",
    culture_reference: "Archival runway, fashion Tumblr, runway video culture",
    visual_prompt: "vintage runway archival fashion dramatic silhouettes editorial mythology",
    content_excerpt: "Why it matters: archival runway gives people a vocabulary for drama that current algorithms often flatten.",
    image_strategy: "gradient",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1022-4222-8222-222222222222",
    title: "The Indian Blouse Is Having a Main Character Moment",
    subtitle: "Back details, sleeves, necklines, tie-ups, and embroidery are turning the blouse into the outfit's thesis.",
    slug: "indian-blouse-main-character",
    cover_image_url: null,
    category: "Indian fashion culture",
    tags: ["blouse", "sari", "Indian tailoring"],
    archetypes: ["Romantic", "Avant-Garde", "Classic"],
    reading_time: 5,
    date: "2026-05-07",
    mood: "ornate",
    era: "2020s",
    region: "India",
    culture_reference: "Contemporary sari blouses, Indian bridal and festive tailoring",
    visual_prompt: "Indian blouse design editorial back detail embroidery sari styling",
    content_excerpt: "Why it matters: the blouse is where tradition, body confidence, and trend experimentation meet.",
    image_strategy: "typography",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1023-4222-8222-222222222222",
    title: "Why Y2K Came Back Softer",
    subtitle: "Low-rise chaos returned with baby tees, gloss, denim, metallics, and a little more self-awareness.",
    slug: "y2k-came-back-softer",
    cover_image_url: null,
    category: "Trend intelligence",
    tags: ["Y2K", "denim", "nostalgia"],
    archetypes: ["Street Muse", "Romantic"],
    reading_time: 4,
    date: "2026-05-06",
    mood: "glossy",
    era: "Y2K",
    region: "Global",
    culture_reference: "2000s pop culture, mall fashion, Instagram revival aesthetics",
    visual_prompt: "Y2K fashion baby tee denim gloss street style editorial magazine",
    content_excerpt: "Why it matters: Y2K is not just nostalgia. It is a return to visible personality after years of muted minimalism.",
    image_strategy: "collage",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1024-4222-8222-222222222222",
    title: "The Quiet Luxury Lie",
    subtitle: "Quiet luxury sells restraint, but real style is not quiet unless the wearer wants it to be.",
    slug: "quiet-luxury-lie",
    cover_image_url: null,
    category: "Trend intelligence",
    tags: ["quiet luxury", "class", "minimalism"],
    archetypes: ["Minimalist", "Classic", "Avant-Garde"],
    reading_time: 6,
    date: "2026-05-05",
    mood: "critical",
    era: "2020s",
    region: "Global",
    culture_reference: "Quiet luxury, succession dressing, stealth wealth",
    visual_prompt: "quiet luxury neutral wardrobe critical editorial cashmere blazer",
    content_excerpt: "Why it matters: the trend often confuses taste with class signals. That difference matters.",
    image_strategy: "gradient",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1025-4222-8222-222222222222",
    title: "How Shoes Changed Street Style",
    subtitle: "Sneakers, ballet flats, loafers, boots, and kolhapuris can redirect the entire meaning of a look.",
    slug: "shoes-changed-street-style",
    cover_image_url: null,
    category: "Trend intelligence",
    tags: ["shoes", "street style", "styling"],
    archetypes: ["Street Muse", "Classic", "Bohemian"],
    reading_time: 4,
    date: "2026-05-04",
    mood: "grounded",
    era: "2010s-now",
    region: "Global",
    culture_reference: "Sneaker culture, ballet flat revival, Indian flats",
    visual_prompt: "street style shoes sneakers ballet flats boots editorial outfit detail",
    content_excerpt: "Why it matters: shoes decide whether the same outfit reads romantic, practical, rebellious, or polished.",
    image_strategy: "typography",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1026-4222-8222-222222222222",
    title: "The Ritual of Getting Ready",
    subtitle: "A playlist, mirror, scent, jewellery tray, and last-minute change can be a private form of styling intelligence.",
    slug: "ritual-of-getting-ready",
    cover_image_url: null,
    category: "Styling rituals",
    tags: ["getting ready", "ritual", "beauty"],
    archetypes: ["Romantic", "Classic", "Bohemian"],
    reading_time: 5,
    date: "2026-05-03",
    mood: "private",
    era: "timeless",
    region: "Global",
    culture_reference: "GRWM culture, beauty rituals, dressing tables",
    visual_prompt: "getting ready ritual fashion jewellery tray mirror cinematic editorial",
    content_excerpt: "Why it matters: style often happens before the outfit appears, in the emotional preparation around it.",
    image_strategy: "collage",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1027-4222-8222-222222222222",
    title: "Designer Stories: The Tailor, the Muse, and the Room",
    subtitle: "Great clothes come from relationships: who is seen, who is shaped, and who is allowed to become more visible.",
    slug: "tailor-muse-room",
    cover_image_url: null,
    category: "Designer stories",
    tags: ["designer", "tailoring", "muse"],
    archetypes: ["Classic", "Romantic", "Avant-Garde"],
    reading_time: 7,
    date: "2026-05-02",
    mood: "observant",
    era: "timeless",
    region: "Global",
    culture_reference: "Atelier culture, tailoring rooms, designer-muse relationships",
    visual_prompt: "fashion atelier tailor muse fitting room editorial documentary",
    content_excerpt: "Why it matters: clothing is never only product. It is negotiation between body, maker, mood, and room.",
    image_strategy: "typography",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1028-4222-8222-222222222222",
    title: "Monsoon Romance, City Edge",
    subtitle: "Wet pavement, cotton, oxidised silver, dark denim, and silk make rainy dressing feel cinematic.",
    slug: "monsoon-romance-city-edge",
    cover_image_url: null,
    category: "Moodboards",
    tags: ["monsoon", "city", "romance"],
    archetypes: ["Romantic", "Street Muse", "Bohemian"],
    reading_time: 4,
    date: "2026-05-01",
    mood: "rain-soaked",
    era: "modern",
    region: "India",
    culture_reference: "Indian monsoon, city dressing, romantic street style",
    visual_prompt: "Indian monsoon fashion city rain wet pavement silk denim oxidised silver editorial",
    content_excerpt: "Why it matters: weather can become styling direction instead of an inconvenience.",
    image_strategy: "collage",
    is_featured: true,
  }),
  makeArticle({
    id: "22222222-1029-4222-8222-222222222222",
    title: "How Avant-Garde Silhouettes Teach Courage",
    subtitle: "A strange sleeve, sculptural skirt, hard shoulder, or asymmetrical hem trains the eye to accept a new self.",
    slug: "avant-garde-silhouettes-teach-courage",
    cover_image_url: null,
    category: "Style psychology",
    tags: ["avant-garde", "silhouette", "courage"],
    archetypes: ["Avant-Garde", "Minimalist"],
    reading_time: 6,
    date: "2026-04-30",
    mood: "brave",
    era: "runway",
    region: "Global",
    culture_reference: "Japanese designers, Antwerp Six, sculptural runway",
    visual_prompt: "avant garde silhouettes sculptural fashion runway editorial black white",
    content_excerpt: "Why it matters: wearing an unusual shape is a small practice in being seen before being understood.",
    image_strategy: "gradient",
    is_featured: false,
  }),
  makeArticle({
    id: "22222222-1030-4222-8222-222222222222",
    title: "The Wardrobe as a Private Archive",
    subtitle: "Old shirts, gifted jewellery, travel scarves, and repeated dresses become a record of who you were becoming.",
    slug: "wardrobe-private-archive",
    cover_image_url: null,
    category: "Style psychology",
    tags: ["memory", "wardrobe", "archive"],
    archetypes: ["Romantic", "Classic", "Bohemian"],
    reading_time: 6,
    date: "2026-04-29",
    mood: "remembering",
    era: "timeless",
    region: "Global",
    culture_reference: "Personal archives, heirlooms, sentimental clothing",
    visual_prompt: "wardrobe private archive old clothes jewellery memory editorial still life",
    content_excerpt: "Why it matters: some clothes are kept because they still know a version of us.",
    image_strategy: "typography",
    is_featured: false,
  }),
];

export const seedMicroDocs: MicroDocumentary[] = [
  {
    id: "33333333-1001-4333-8333-333333333333",
    title: "60 Seconds on the Sari",
    description: "One drape, infinite identities.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "Indian fashion culture",
    tags: ["sari", "drape"],
    archetypes: ["Romantic", "Classic", "Bohemian"],
    visual_prompt: "vertical film Indian sari drape heritage modern editorial",
    image_strategy: "typography",
  },
  {
    id: "33333333-1002-4333-8333-333333333333",
    title: "The Rise of the Indian Romantic Muse",
    description: "Chiffon, gold, kajal, and soft power.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "culture",
    tags: ["Indian muse", "romantic"],
    archetypes: ["Romantic", "Classic"],
    visual_prompt: "Indian romantic muse old Bollywood chiffon gold cinematic vertical",
    image_strategy: "collage",
  },
  {
    id: "33333333-1003-4333-8333-333333333333",
    title: "Why Black Always Wins",
    description: "Protection, elegance, rebellion, silence.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "psychology",
    tags: ["black", "identity"],
    archetypes: ["Minimalist", "Avant-Garde", "Classic"],
    visual_prompt: "all black fashion vertical editorial silhouette psychological",
    image_strategy: "gradient",
  },
  {
    id: "33333333-1004-4333-8333-333333333333",
    title: "How Y2K Came Back",
    description: "Gloss, denim, baby tees, and nostalgia.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "trend intelligence",
    tags: ["Y2K", "nostalgia"],
    archetypes: ["Street Muse", "Romantic"],
    visual_prompt: "Y2K vertical fashion film denim gloss street style",
    image_strategy: "collage",
  },
  {
    id: "33333333-1005-4333-8333-333333333333",
    title: "The Gold Jewellery Effect",
    description: "How one metal changes the face.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "styling rituals",
    tags: ["gold jewellery", "face framing"],
    archetypes: ["Romantic", "Classic", "Bohemian"],
    visual_prompt: "gold jewellery Indian portrait vertical warm cinematic",
    image_strategy: "typography",
  },
  {
    id: "33333333-1006-4333-8333-333333333333",
    title: "The Quiet Luxury Lie",
    description: "When restraint becomes a class signal.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "trend intelligence",
    tags: ["quiet luxury", "minimalism"],
    archetypes: ["Minimalist", "Classic"],
    visual_prompt: "quiet luxury neutral vertical editorial critical fashion",
    image_strategy: "gradient",
  },
  {
    id: "33333333-1007-4333-8333-333333333333",
    title: "Why Old Bollywood Still Dresses Us",
    description: "The sari, liner, hair, and hand gesture.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "history",
    tags: ["old Bollywood", "Indian cinema"],
    archetypes: ["Romantic", "Classic"],
    visual_prompt: "old Bollywood fashion vertical archive inspired Indian cinema",
    image_strategy: "collage",
  },
  {
    id: "33333333-1008-4333-8333-333333333333",
    title: "How Shoes Changed Street Style",
    description: "Sneakers, flats, boots, and the outfit's final verb.",
    video_url: "https://videos.pexels.com/video-files/853848/853848-hd_1920_1080_25fps.mp4",
    thumbnail_url: null,
    duration_seconds: 60,
    category: "street style",
    tags: ["shoes", "street style"],
    archetypes: ["Street Muse", "Classic"],
    visual_prompt: "street style shoe details vertical documentary sneakers flats boots",
    image_strategy: "typography",
  },
];

export const seedQuizQuestions: StyleQuizQuestion[] = [
  {
    id: "44444444-0001-4444-8444-444444444444",
    question: "What makes you save an outfit instantly?",
    options: [
      { label: "Soft drape and emotion", archetype: "Romantic", colors: ["rose", "ivory"], moods: ["dreamy"] },
      { label: "Clean lines and restraint", archetype: "Minimalist", colors: ["black", "bone"], moods: ["quiet"] },
      { label: "A shape nobody else would wear", archetype: "Avant-Garde", colors: ["black", "chrome"], moods: ["strange"] },
    ],
  },
  {
    id: "44444444-0002-4444-8444-444444444444",
    question: "Which detail feels most like you?",
    options: [
      { label: "A perfect blazer shoulder", archetype: "Classic", eras: ["1990s"], moods: ["polished"] },
      { label: "Oversized denim and sneakers", archetype: "Street Muse", eras: ["2010s"], moods: ["kinetic"] },
      { label: "Print, texture, and movement", archetype: "Bohemian", eras: ["1970s"], moods: ["earthy"] },
    ],
  },
  {
    id: "44444444-0003-4444-8444-444444444444",
    question: "Pick the fashion world you want to enter.",
    options: [
      { label: "Paris after dark", archetype: "Romantic", colors: ["black", "wine"], moods: ["cinematic"] },
      { label: "Tokyo concept store", archetype: "Avant-Garde", colors: ["black", "silver"], moods: ["architectural"] },
      { label: "Seoul street corner", archetype: "Street Muse", colors: ["charcoal", "indigo"], moods: ["youthful"] },
    ],
  },
  {
    id: "44444444-0004-4444-8444-444444444444",
    question: "Your ideal outfit changes your...",
    options: [
      { label: "Presence", archetype: "Classic", moods: ["composed"] },
      { label: "Mood", archetype: "Romantic", moods: ["expressive"] },
      { label: "Silhouette", archetype: "Avant-Garde", moods: ["sculptural"] },
    ],
  },
  {
    id: "44444444-0005-4444-8444-444444444444",
    question: "Choose a texture.",
    options: [
      { label: "Raw denim", archetype: "Street Muse", moods: ["worn-in"] },
      { label: "Crisp cotton", archetype: "Minimalist", moods: ["clean"] },
      { label: "Embroidered cotton", archetype: "Bohemian", moods: ["handmade"] },
    ],
  },
  {
    id: "44444444-0006-4444-8444-444444444444",
    question: "Which era keeps pulling you in?",
    options: [
      { label: "The 70s", archetype: "Bohemian", eras: ["1970s"] },
      { label: "The 90s", archetype: "Minimalist", eras: ["1990s"] },
      { label: "The future", archetype: "Avant-Garde", eras: ["future"] },
    ],
  },
  {
    id: "44444444-0007-4444-8444-444444444444",
    question: "What do you want clothes to do first?",
    options: [
      { label: "Make me feel softer", archetype: "Romantic" },
      { label: "Make me look sharper", archetype: "Classic" },
      { label: "Make me look current", archetype: "Street Muse" },
    ],
  },
  {
    id: "44444444-0008-4444-8444-444444444444",
    question: "Pick a closet rule.",
    options: [
      { label: "Less, but better", archetype: "Minimalist" },
      { label: "One dramatic piece", archetype: "Avant-Garde" },
      { label: "Always add texture", archetype: "Bohemian" },
    ],
  },
];

export const seedWeeklyMood: StyleMoodWeekly = {
  id: "55555555-5555-4555-8555-555555555555",
  week_start: "2026-05-25",
  title: "Monsoon Romance, City Edge",
  description:
    "Wet pavement, silk, oxidised silver, cotton, denim, and antique gold. The mood is cinematic, intimate, and a little rebellious.",
  colors: ["#111113", "#f3eee7", "#9d6474", "#b39252", "#53687c"],
  textures: ["wet pavement", "silk", "oxidised silver", "cotton", "denim"],
  keywords: ["cinematic", "intimate", "soft rebellion", "Indian romantic", "city muse"],
  image_board_urls: [],
  linked_articles: [
    "22222222-1028-4222-8222-222222222222",
    "22222222-1001-4222-8222-222222222222",
  ],
};
