import { addDays } from "date-fns";
import type {
  CategoryRecord,
  DashboardStats,
  ProductRecord,
  ScrapeRunRecord,
  SourceRecord,
  TrendKeywordRecord,
  TrendRow,
  TrendSnapshotRecord,
} from "@/lib/types";

const now = new Date();

function iso(daysOffset: number) {
  return addDays(now, daysOffset).toISOString();
}

export const mockSources: SourceRecord[] = [
  { id: 1, name: "Myntra", base_url: "https://www.myntra.com", created_at: iso(-30) },
  { id: 2, name: "Ajio", base_url: "https://www.ajio.com", created_at: iso(-30) },
  { id: 3, name: "Zara India", base_url: "https://www.zara.com/in", created_at: iso(-30) },
  { id: 4, name: "H&M India", base_url: "https://www2.hm.com/en_in/index.html", created_at: iso(-30) },
  { id: 5, name: "Nykaa Fashion", base_url: "https://www.nykaafashion.com", created_at: iso(-30) },
];

export const mockCategories: CategoryRecord[] = [
  { id: 1, name: "Women Tops", created_at: iso(-30) },
  { id: 2, name: "Women Bottomwear", created_at: iso(-30) },
  { id: 3, name: "Men Shirts", created_at: iso(-30) },
  { id: 4, name: "Dresses", created_at: iso(-30) },
  { id: 5, name: "Outerwear", created_at: iso(-30) },
  { id: 6, name: "Accessories", created_at: iso(-30) },
];

export const mockTrendKeywords: TrendKeywordRecord[] = [
  "oversized",
  "baggy",
  "cargo",
  "denim",
  "linen",
  "washed",
  "vintage",
  "graphic",
  "cropped",
  "varsity",
  "utility",
  "minimal",
  "co-ord",
  "streetwear",
  "relaxed fit",
  "wide leg",
  "slim fit",
  "satin",
  "suede",
  "leather",
  "knit",
  "mesh",
  "floral",
  "monochrome",
  "earth tones",
  "brown",
  "beige",
  "grey",
  "black",
  "white",
].map((keyword, index) => ({
  id: index + 1,
  keyword,
  category:
    keyword === "brown" || keyword === "beige" || keyword === "grey" || keyword === "black" || keyword === "white"
      ? "color"
      : keyword.includes("fit") || keyword.includes("wide") || keyword.includes("oversized") || keyword.includes("baggy")
        ? "silhouette"
        : "style",
  created_at: iso(-30),
}));

export const mockProducts: ProductRecord[] = [
  {
    id: 1,
    source_id: 1,
    category_id: 1,
    title: "Oversized linen shirt in beige",
    brand: "Roadster",
    price: 1799,
    original_price: 2299,
    discount_percentage: 22,
    color: "Beige",
    image_url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&q=80",
    product_url: "https://www.myntra.com/oversized-linen-shirt-beige",
    scraped_at: iso(-2),
    created_at: iso(-2),
  },
  {
    id: 2,
    source_id: 1,
    category_id: 2,
    title: "Baggy cargo trousers with utility pockets",
    brand: "H&M",
    price: 2499,
    original_price: 2999,
    discount_percentage: 17,
    color: "Khaki",
    image_url: "https://images.unsplash.com/photo-1475180098004-ca77a6537186?w=800&q=80",
    product_url: "https://www.myntra.com/baggy-cargo-trousers",
    scraped_at: iso(-1),
    created_at: iso(-1),
  },
  {
    id: 3,
    source_id: 2,
    category_id: 4,
    title: "Floral co-ord dress set in white",
    brand: "AJIO",
    price: 3299,
    original_price: 4999,
    discount_percentage: 34,
    color: "White",
    image_url: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80",
    product_url: "https://www.ajio.com/floral-co-ord-dress-set",
    scraped_at: iso(-3),
    created_at: iso(-3),
  },
  {
    id: 4,
    source_id: 2,
    category_id: 3,
    title: "Relaxed fit denim shirt in grey",
    brand: "DNMX",
    price: 1599,
    original_price: 2199,
    discount_percentage: 27,
    color: "Grey",
    image_url: "https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=800&q=80",
    product_url: "https://www.ajio.com/relaxed-fit-denim-shirt-grey",
    scraped_at: iso(-4),
    created_at: iso(-4),
  },
  {
    id: 5,
    source_id: 3,
    category_id: 1,
    title: "Minimal cropped knit top",
    brand: "ZARA",
    price: 2590,
    original_price: 2590,
    discount_percentage: 0,
    color: "Black",
    image_url: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80",
    product_url: "https://www.zara.com/in/en/minimal-cropped-knit-top",
    scraped_at: iso(-1),
    created_at: iso(-1),
  },
  {
    id: 6,
    source_id: 3,
    category_id: 5,
    title: "Wide leg utility trousers",
    brand: "ZARA",
    price: 3990,
    original_price: 4990,
    discount_percentage: 20,
    color: "Brown",
    image_url: "https://images.unsplash.com/photo-1485470733090-0aae1788d5af?w=800&q=80",
    product_url: "https://www.zara.com/in/en/wide-leg-utility-trousers",
    scraped_at: iso(-2),
    created_at: iso(-2),
  },
  {
    id: 7,
    source_id: 4,
    category_id: 1,
    title: "Monochrome oversized graphic tee",
    brand: "H&M",
    price: 999,
    original_price: 1499,
    discount_percentage: 33,
    color: "Black",
    image_url: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80",
    product_url: "https://www2.hm.com/en_in/product/monochrome-oversized-graphic-tee",
    scraped_at: iso(-2),
    created_at: iso(-2),
  },
  {
    id: 8,
    source_id: 4,
    category_id: 5,
    title: "Washed denim jacket with relaxed fit",
    brand: "H&M",
    price: 3499,
    original_price: 3999,
    discount_percentage: 13,
    color: "Blue",
    image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
    product_url: "https://www2.hm.com/en_in/product/washed-denim-jacket-relaxed-fit",
    scraped_at: iso(-6),
    created_at: iso(-6),
  },
  {
    id: 9,
    source_id: 5,
    category_id: 4,
    title: "Satin floral midi dress",
    brand: "MANGO",
    price: 4599,
    original_price: 5999,
    discount_percentage: 23,
    color: "Pink",
    image_url: "https://images.unsplash.com/photo-1496747611182-9e3f9d4f2e0f?w=800&q=80",
    product_url: "https://www.nykaafashion.com/satin-floral-midi-dress",
    scraped_at: iso(-3),
    created_at: iso(-3),
  },
  {
    id: 10,
    source_id: 5,
    category_id: 6,
    title: "Leather shoulder bag in brown",
    brand: "Lino Perros",
    price: 2899,
    original_price: 3499,
    discount_percentage: 17,
    color: "Brown",
    image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    product_url: "https://www.nykaafashion.com/leather-shoulder-bag-brown",
    scraped_at: iso(-4),
    created_at: iso(-4),
  },
  {
    id: 11,
    source_id: 1,
    category_id: 3,
    title: "Slim fit striped shirt in white",
    brand: "Roadster",
    price: 1399,
    original_price: 1999,
    discount_percentage: 30,
    color: "White",
    image_url: "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80",
    product_url: "https://www.myntra.com/slim-fit-striped-shirt-white",
    scraped_at: iso(-8),
    created_at: iso(-8),
  },
  {
    id: 12,
    source_id: 2,
    category_id: 2,
    title: "Wide leg linen pants in beige",
    brand: "The Souled Store",
    price: 2199,
    original_price: 2799,
    discount_percentage: 21,
    color: "Beige",
    image_url: "https://images.unsplash.com/photo-1506629905607-d9c6b63f1b7b?w=800&q=80",
    product_url: "https://www.ajio.com/wide-leg-linen-pants-beige",
    scraped_at: iso(-7),
    created_at: iso(-7),
  },
  {
    id: 13,
    source_id: 3,
    category_id: 1,
    title: "Streetwear graphic cropped hoodie",
    brand: "ZARA",
    price: 3990,
    original_price: 4990,
    discount_percentage: 20,
    color: "Grey",
    image_url: "https://images.unsplash.com/photo-1523395255812-76b0a3f95d07?w=800&q=80",
    product_url: "https://www.zara.com/in/en/streetwear-graphic-cropped-hoodie",
    scraped_at: iso(-2),
    created_at: iso(-2),
  },
  {
    id: 14,
    source_id: 4,
    category_id: 3,
    title: "Vintage washed overshirt in utility style",
    brand: "H&M",
    price: 2799,
    original_price: 3299,
    discount_percentage: 15,
    color: "Olive",
    image_url: "https://images.unsplash.com/photo-1484516758160-69858111bb77?w=800&q=80",
    product_url: "https://www2.hm.com/en_in/product/vintage-washed-overshirt-utility",
    scraped_at: iso(-5),
    created_at: iso(-5),
  },
  {
    id: 15,
    source_id: 5,
    category_id: 2,
    title: "Baggy relaxed fit jeans in black",
    brand: "ONLY",
    price: 3099,
    original_price: 3999,
    discount_percentage: 22,
    color: "Black",
    image_url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80",
    product_url: "https://www.nykaafashion.com/baggy-relaxed-fit-jeans-black",
    scraped_at: iso(-1),
    created_at: iso(-1),
  },
  {
    id: 16,
    source_id: 1,
    category_id: 4,
    title: "Earth tones floral midi dress",
    brand: "Mango",
    price: 3899,
    original_price: 4899,
    discount_percentage: 20,
    color: "Brown",
    image_url: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80",
    product_url: "https://www.myntra.com/earth-tones-floral-midi-dress",
    scraped_at: iso(-6),
    created_at: iso(-6),
  },
  {
    id: 17,
    source_id: 2,
    category_id: 5,
    title: "Leather jacket in black",
    brand: "Rare Rabbit",
    price: 6499,
    original_price: 7999,
    discount_percentage: 19,
    color: "Black",
    image_url: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&q=80",
    product_url: "https://www.ajio.com/leather-jacket-black",
    scraped_at: iso(-6),
    created_at: iso(-6),
  },
  {
    id: 18,
    source_id: 3,
    category_id: 1,
    title: "Minimal knit top in white",
    brand: "ZARA",
    price: 2590,
    original_price: 2590,
    discount_percentage: 0,
    color: "White",
    image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
    product_url: "https://www.zara.com/in/en/minimal-knit-top-white",
    scraped_at: iso(-8),
    created_at: iso(-8),
  },
  {
    id: 19,
    source_id: 4,
    category_id: 2,
    title: "Utility cargo shorts in beige",
    brand: "H&M",
    price: 1299,
    original_price: 1799,
    discount_percentage: 28,
    color: "Beige",
    image_url: "https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=800&q=80",
    product_url: "https://www2.hm.com/en_in/product/utility-cargo-shorts-beige",
    scraped_at: iso(-3),
    created_at: iso(-3),
  },
  {
    id: 20,
    source_id: 5,
    category_id: 6,
    title: "Monochrome suede loafers",
    brand: "Aldo",
    price: 5299,
    original_price: 6999,
    discount_percentage: 24,
    color: "Black",
    image_url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    product_url: "https://www.nykaafashion.com/monochrome-suede-loafers",
    scraped_at: iso(-5),
    created_at: iso(-5),
  },
  {
    id: 21,
    source_id: 1,
    category_id: 1,
    title: "Graphic tee with varsity print",
    brand: "HRX",
    price: 1099,
    original_price: 1599,
    discount_percentage: 31,
    color: "White",
    image_url: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80",
    product_url: "https://www.myntra.com/graphic-tee-varsity-print",
    scraped_at: iso(-2),
    created_at: iso(-2),
  },
  {
    id: 22,
    source_id: 2,
    category_id: 3,
    title: "Relaxed fit linen shirt in grey",
    brand: "Ajio",
    price: 1899,
    original_price: 2499,
    discount_percentage: 24,
    color: "Grey",
    image_url: "https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=800&q=80",
    product_url: "https://www.ajio.com/relaxed-fit-linen-shirt-grey",
    scraped_at: iso(-1),
    created_at: iso(-1),
  },
  {
    id: 23,
    source_id: 3,
    category_id: 5,
    title: "Oversized suede jacket in brown",
    brand: "ZARA",
    price: 8990,
    original_price: 10990,
    discount_percentage: 18,
    color: "Brown",
    image_url: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&q=80",
    product_url: "https://www.zara.com/in/en/oversized-suede-jacket-brown",
    scraped_at: iso(-4),
    created_at: iso(-4),
  },
  {
    id: 24,
    source_id: 4,
    category_id: 4,
    title: "Floral satin dress in beige",
    brand: "H&M",
    price: 2899,
    original_price: 3599,
    discount_percentage: 19,
    color: "Beige",
    image_url: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80",
    product_url: "https://www2.hm.com/en_in/product/floral-satin-dress-beige",
    scraped_at: iso(-7),
    created_at: iso(-7),
  },
  {
    id: 25,
    source_id: 5,
    category_id: 6,
    title: "Minimal monochrome shoulder bag",
    brand: "Charles & Keith",
    price: 4999,
    original_price: 5999,
    discount_percentage: 17,
    color: "Black",
    image_url: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&q=80",
    product_url: "https://www.nykaafashion.com/minimal-monochrome-shoulder-bag",
    scraped_at: iso(-2),
    created_at: iso(-2),
  },
];

export const mockScrapeRuns: ScrapeRunRecord[] = [
  {
    id: 1,
    source_id: 1,
    category_id: 1,
    status: "completed",
    started_at: iso(-1),
    completed_at: iso(-1),
    products_found: 14,
    error_message: null,
  },
  {
    id: 2,
    source_id: 3,
    category_id: 5,
    status: "running",
    started_at: iso(0),
    completed_at: null,
    products_found: 0,
    error_message: null,
  },
];

export const mockTrendSnapshots: TrendSnapshotRecord[] = [];

export type MockDataset = {
  sources: SourceRecord[];
  categories: CategoryRecord[];
  products: ProductRecord[];
  scrapeRuns: ScrapeRunRecord[];
  trendKeywords: TrendKeywordRecord[];
  trendSnapshots: TrendSnapshotRecord[];
};

export const mockDataset: MockDataset = {
  sources: mockSources,
  categories: mockCategories,
  products: mockProducts,
  scrapeRuns: mockScrapeRuns,
  trendKeywords: mockTrendKeywords,
  trendSnapshots: mockTrendSnapshots,
};

export function makeMockDashboardStats(topRisingTrends: TrendRow[], topDecliningTrends: TrendRow[], commonColors: Array<{ color: string; count: number }>, averagePriceByCategory: Array<{ category: string; averagePrice: number }>): DashboardStats {
  const brandCount = new Set(mockProducts.map((product) => product.brand).filter(Boolean)).size;
  const latestRun = [...mockScrapeRuns].sort((a, b) => b.started_at.localeCompare(a.started_at))[0];

  return {
    totalProducts: mockProducts.length,
    totalBrands: brandCount,
    topRisingTrends,
    topDecliningTrends,
    commonColors,
    averagePriceByCategory,
    latestScrapeStatus: {
      status: latestRun?.status ?? "idle",
      startedAt: latestRun?.started_at ?? null,
      completedAt: latestRun?.completed_at ?? null,
      productsFound: latestRun?.products_found ?? 0,
      errorMessage: latestRun?.error_message ?? null,
      sourceName: "Myntra",
      categoryName: "Women Tops",
    },
  };
}
