#!/usr/bin/env node
import "./load-env";
import { MANUAL_STYLING_STAGES, MANUAL_STYLING_WORKFLOW_NAME, runManualFirstStylingWorkflow } from "../lib/trend-styling/manual-workflow";
import { createConfiguredMarketInterestProvider, createSupabaseResearchStore, runResearchWorker } from "../lib/trend-styling/research-worker";
import { createStylingEvidenceSearchProvider } from "../lib/trend-styling/evidence-provider";
import { buildEvidenceGroundedFormulaPrompt } from "../lib/trend-styling/formula-generation";
import { createFormulaTextProvider } from "../lib/trend-styling/providers";
import { stageAndAtomicallyApproveFormulaSet } from "../lib/trend-styling/atomic-formula-publication";
import { getSupabaseClient } from "../lib/supabase";
import type { TrendStyleEvidence } from "../lib/trend-styling/schema";

async function main(){const execute=process.argv.includes("--execute");const enabled=process.env.TREND_STYLING_INTELLIGENCE_ENABLED==="true";const autoImages=process.env.AUTO_ENQUEUE_FORMULA_IMAGES_ENABLED==="true";if(!execute){console.log(JSON.stringify({workflow:MANUAL_STYLING_WORKFLOW_NAME,dryRun:true,enabled,autoEnqueueFormulaImages:autoImages,stages:MANUAL_STYLING_STAGES},null,2));return;}if(!enabled)throw new Error("Manual styling execution is disabled by TREND_STYLING_INTELLIGENCE_ENABLED");let researchResult:any;const result=await runManualFirstStylingWorkflow({enabled,autoEnqueueImages:autoImages,research:async()=>{researchResult=await runResearchWorker({workerId:`manual-${process.pid}`,store:createSupabaseResearchStore(),interestProvider:createConfiguredMarketInterestProvider(),searchProvider:createStylingEvidenceSearchProvider()});if(researchResult.status!=="completed")throw new Error(`Research worker ${researchResult.status}`);return {evidence:researchResult.evidence};},generate:async(evidence)=>{const job=researchResult.job;const typed=evidence.map((item:any)=>({...item,trend_id:null})) as TrendStyleEvidence[];const prompt=buildEvidenceGroundedFormulaPrompt({conceptId:job.concept_id,canonicalKeyword:job.canonical_keyword,season:job.season,requestingMarket:job.requesting_market,marketPlan:researchResult.marketPlan,evidence:typed});return createFormulaTextProvider().generate({prompt});},approve:async(formulas)=>(await stageAndAtomicallyApproveFormulaSet(formulas)).formulas,enqueue:async(jobs)=>{const db=getSupabaseClient();if(!db)throw new Error("Supabase required");const {error}=await db.from("image_generation_jobs").insert(jobs);if(error)throw error;}});console.log(JSON.stringify({workflow:MANUAL_STYLING_WORKFLOW_NAME,status:result.status,formulaCount:"formulas" in result?result.formulas?.length||0:0,imageJobs:"jobs" in result?result.jobs?.length||0:0},null,2));}
main().catch((error)=>{console.error(error);process.exitCode=1;});
